### ISSUE TITLE
cap  An unhandled exception was thrown by the application.

### ISSUE THREAD

**Issue by henrydingchina** [dotnetcore/CAP#1001]
`2021-09-17 14:16:53,824 [221] WARN - DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.? : Get messages of type 'MediumMessage' failed. Retrying...
System.TypeLoadException: Could not load type 'DotNetCore.CAP.Serialization.StringSerializer' from assembly 'DotNetCore.CAP, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null'.
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetPublishedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetPublishedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
2021-09-17 14:16:53,834 [221] WARN - DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.? : Get messages of type 'MediumMessage' failed. Retrying...
System.TypeLoadException: Could not load type 'DotNetCore.CAP.Serialization.StringSerializer' from assembly 'DotNetCore.CAP, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null'.
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetReceivedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetReceivedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
2021-09-17 14:16:58,101 [221] INFO - Microsoft.AspNetCore.Hosting.Diagnostics.? : Request starting HTTP/1.1 GET http://localhost:3078/vfs/cap
2021-09-17 14:16:58,108 [221] ERROR- Microsoft.AspNetCore.Server.Kestrel.? : Connection id "0HMBPK132O62L", Request id "0HMBPK132O62L:00000005": An unhandled exception was thrown by the application.
System.TypeLoadException: Method 'Messages' in type 'DotNetCore.CAP.MySql.MySqlMonitoringApi' from assembly 'DotNetCore.CAP.MySql, Version=3.0.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetMonitoringApi()
   at DotNetCore.CAP.Dashboard.Pages.HomePage.Execute()
   at DotNetCore.CAP.Dashboard.RazorPage.TransformText(String body)
   at DotNetCore.CAP.Dashboard.RazorPage.ToString()
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

Does anyone know why?

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
