### ISSUE TITLE
ERROR- DotNetCore.CAP.Processor.Dispatcher.? : An exception occurred when sending a message to the MQ.

### ISSUE THREAD

**Issue by henrydingchina** [dotnetcore/CAP#1002]
I want to integrate CAP into my project,
But I have a problem?

cap v3.0.0
cap.dashboard v3.0.0
cap.mysql v3.0.0
cap.rabbitmq v3.0.0
I tried to send a message to MQ using CAP

`

 [HttpGet("pub")]

        public void Pub()

        {

            m_capPublisher.PublishAsync("12",

                new CameraDetectionTaskQuartzIntegrationEvent("1"));

        }

`
 

But I have this problem

`
ERROR- DotNetCore.CAP.Processor.Dispatcher.? : An exception occurred when sending a message to the MQ. Id:1438815636284850176
System.MissingMethodException: Method not found: 'Void RabbitMQ.Client.IModelExensions.BasicPublish(RabbitMQ.Client.IModel, System.String, System.String, RabbitMQ.Client.IBasicProperties, Byte[])'.
   at DotNetCore.CAP.RabbitMQ.RabbitMQTransport.SendAsync(TransportMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendWithoutRetryAsync(MediumMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendAsync(MediumMessage message)
   at DotNetCore.CAP.Processor.Dispatcher.Sending()
`

May I ask what caused the problem?

**Comment by xiangxiren** [comment]
Please report your RabbitMQ version

**Comment by henrydingchina** [comment]
![image](https://user-images.githubusercontent.com/79189526/133867881-a4130cf8-3138-486d-8a5f-de872bef1022.png)

>6.0

**Comment by henrydingchina** [comment]
> 请报告您的RabbitMQ版本

![image](https://user-images.githubusercontent.com/79189526/133867992-7351b69e-4370-435e-9257-b903b1500ffd.png)

**Comment by xiangxiren** [comment]
![image](https://user-images.githubusercontent.com/12774053/133868027-d607eac7-5b0c-41be-ad06-1f9cadcf9388.png)

**Comment by henrydingchina** [comment]
My MQ version is >5.1.0, I can't figure out why,  

![image](https://user-images.githubusercontent.com/79189526/133868627-46b36306-0af7-47f9-8a4b-f3d30afa12a6.png)

**Comment by henrydingchina** [comment]
![image](https://user-images.githubusercontent.com/79189526/133868646-b17049fe-1bb9-44aa-85b1-5a434dbe065a.png)

This error still exists, looks like there is nothing wrong with my version

**Comment by xiangxiren** [comment]
If you use the 3.0 version of CAP. Then the version of Rabbit.Client must be greater than or equal to 5.1.0 and less than 6.0.0

**Comment by xiangxiren** [comment]
Rabbit.Client 5.x:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/3fb81a44d29aaba55a4b01a866f57f0830b22249/projects/client/RabbitMQ.Client/src/client/api/IModelExtensions.cs#L102

6.x:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/503580ace7f5c726b157f68da3888104315e5947/projects/RabbitMQ.Client/client/api/IModelExtensions.cs#L94

**Comment by henrydingchina** [comment]
Thank you for answering my question !

I have upgraded cap to.3.1.2, there is no problem with mq dependency, but my message does not seem to be sent?  

`
 WARN - DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.? : Get messages of type 'MediumMessage' failed. Retrying...
System.TypeLoadException: Could not load type 'DotNetCore.CAP.Serialization.StringSerializer' from assembly 'DotNetCore.CAP, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null'.
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetPublishedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetPublishedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
2021-09-18 10:54:46,761 [100] WARN - DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.? : Get messages of type 'MediumMessage' failed. Retrying...
System.TypeLoadException: Could not load type 'DotNetCore.CAP.Serialization.StringSerializer' from assembly 'DotNetCore.CAP, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null'.
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetReceivedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.MySql.MySqlDataStorage.GetReceivedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
`

**Comment by xiangxiren** [comment]
Make sure all your packages are version v3.1.2
dotnetcore.cap v3.1.2
dotnetcore.cap.dashboard v3.1.2
dotnetcore.cap.mysql v3.1.2
dotnetcore.cap.rabbitmq v3.1.2

**Comment by henrydingchina** [comment]
My mysqlConnector is less than 1.0.0

**Comment by xiangxiren** [comment]
> My mysqlConnector is less than 1.0.0
You need to upgrade MysqlConnector

**Comment by henrydingchina** [comment]
![image](https://user-images.githubusercontent.com/79189526/133874021-7153f603-823d-4df7-9077-619822a820c3.png)

`
InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> 
`
I have upgraded the version, but there is a new problem?

**Comment by henrydingchina** [comment]
2021-09-18 13:34:54,819 [6] INFO - DotNetCore.CAP.Processor.CapProcessingServer.? : Shutting down the processing server...
2021-09-18 13:34:54,820 [6] INFO - DotNetCore.CAP.Processor.CapProcessingServer.? : ### CAP shutdown!

**Comment by henrydingchina** [comment]
内部异常 1:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Logging.ILogger`1[DotNetCore.CAP.Internal.ConsumerRegister], System.IServiceProvider)' on type 'ConsumerRegister'.

内部异常 2:
DependencyResolutionException: An exception was thrown while activating DotNetCore.CAP.Processor.Dispatcher -> DotNetCore.CAP.Internal.MessageSender.

内部异常 3:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Logging.ILogger`1[DotNetCore.CAP.Internal.MessageSender], System.IServiceProvider)' on type 'MessageSender'.

内部异常 4:
DependencyResolutionException: An exception was thrown while activating DotNetCore.CAP.MySql.MySqlDataStorage.

内部异常 5:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[DotNetCore.CAP.MySqlOptions], Microsoft.Extensions.Options.IOptions`1[DotNetCore.CAP.CapOptions], DotNetCore.CAP.Persistence.IStorageInitializer, DotNetCore.CAP.Serialization.ISerializer)' on type 'MySqlDataStorage'.

内部异常 6:
DependencyResolutionException: An exception was thrown while activating VideoFusionService.Extensions.GBDbContext -> DotNetCore.CAP.Internal.CapPublisher.

内部异常 7:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(System.IServiceProvider)' on type 'CapPublisher'.

内部异常 8:
DependencyResolutionException: An exception was thrown while activating DotNetCore.CAP.Processor.Dispatcher -> DotNetCore.CAP.Internal.MessageSender.

内部异常 9:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Logging.ILogger`1[DotNetCore.CAP.Internal.MessageSender], System.IServiceProvider)' on type 'MessageSender'.

内部异常 10:
DependencyResolutionException: An exception was thrown while activating DotNetCore.CAP.MySql.MySqlDataStorage.

内部异常 11:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[DotNetCore.CAP.MySqlOptions], Microsoft.Extensions.Options.IOptions`1[DotNetCore.CAP.CapOptions], DotNetCore.CAP.Persistence.IStorageInitializer, DotNetCore.CAP.Serialization.ISerializer)' on type 'MySqlDataStorage'.

内部异常 12:
InvalidOperationException: ValueFactory attempted to access the Value property of this instance.

`
  services.AddCap(o => 

            { 

                o.UseEntityFramework<GBDbContext>(); 

                o.UseRabbitMQ(opt => 

                { 

                    Configuration.GetSection("RabbitMqConfig").Bind(opt); 

                }); 

            }); 

` 

这是详细的错误，我只升级了cap的包，注入的方式还是和官方给的一样的，哪里有问题呢？

**Comment by henrydingchina** [comment]
当我把cap.mysql升级到3.1.2就会出现这个问题，是缺少什么配置吗？

**Comment by xiangxiren** [comment]
> 当我把cap.mysql升级到3.1.2就会出现这个问题，是缺少什么配置吗？

我这多个系统也是使用3.1.2。并没有出现你这种问题。你可以先建个demo测试一下。

**Comment by xiangxiren** [comment]
你应该使用下面的配置方式：
```
x.UseRabbitMQ(option =>
{
    option.HostName = Configuration["xxx:HostName"];
    option.Port = Configuration.GetValue<int>("xxx:Port");
    option.VirtualHost = Configuration["xxx:VirtualHost"];
    option.UserName = Configuration["xxx:UserName"];
    option.Password = Configuration["xxx:Password"];
});
```
而不是
```
o.UseRabbitMQ(opt => 

            { 

                Configuration.GetSection("RabbitMqConfig").Bind(opt); 

            }); 
```

**Comment by xiangxiren** [comment]
> 当我把cap.mysql升级到3.1.2就会出现这个问题，是缺少什么配置吗？

我们多个系统都使用的3.1.2。并没有出现你这种异常。或许你该认真关注下这个问题
![image](https://user-images.githubusercontent.com/12774053/133880779-ba726e60-cb6d-4267-90af-5b4b67c538dc.png)

**Comment by henrydingchina** [comment]
Autofac.Core.DependencyResolutionException:“An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> DotNetCore.CAP.Internal.ConsumerRegister.”

我看了堆栈信息，但是没有任何头绪。
3.1.2版本是有什么变化吗，我使用3.0.0的没有注入的问题。

**Comment by xiangxiren** [comment]
> 
> 
> Autofac.Core.DependencyResolutionException:“An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> DotNetCore.CAP.Internal.ConsumerRegister.”
> 
> 
> 
> 我看了堆栈信息，但是没有任何头绪。
> 
> 3.1.2版本是有什么变化吗，我使用3.0.0的没有注入的问题。

你可以把3.1.2的代码拉下来调试一下

**Comment by yang-xiaodong** [comment]
closing due to inactivity
