### ISSUE TITLE
Using UseEntityFramework without UseSqlServer throws exception 

### ISSUE THREAD

**Issue by nicholasyin** [dotnetcore/CAP#1007]
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at DotNetCore.CAP.SqlServer.SqlServerStorageInitializer.GetPublishedTableName()
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage..ctor(IOptions`1 capOptions, IOptions`1 options, IStorageInitializer initializer, ISerializer serializer)

**Comment by xiangxiren** [comment]
Please provide the following information:

CAP Version :
Transport :
Storage :
Configuration :
Steps to reproducce :

**Comment by nicholasyin** [comment]
> Did you inject ICapPublisher in DbContext?

Yep. Injecting ICapPublisher in DbContext and UseEntityFramework doesn't seem to like each other.

**Comment by yang-xiaodong** [comment]
@nicholasyin  You can't do this, it will cause circular references.
