### ISSUE TITLE
Error after setting ConsumerThreadCount to 0

### ISSUE THREAD

**Issue by JarFrank** [dotnetcore/CAP#1008]
Hi all!

I found a potentially error
After setting `ProducerThreadCount` or `ConsumerThreadCount` to `0` I get an exception and everything starts to run very slowly.
```
            services.AddCap(options =>
            {
                options.UseInMemoryStorage();
                options.UseRabbitMQ("localhost");
                options.UseDashboard();
                options.ConsumerThreadCount = 0;
            });
```
Logs:
```
fail: DotNetCore.CAP.Internal.Bootstrapper[0]
      Starting the processors throw an exception.
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'capacity')
         at System.Threading.Channels.BoundedChannelOptions..ctor(Int32 capacity)
         at DotNetCore.CAP.Processor.Dispatcher.Start(CancellationToken stoppingToken)
         at DotNetCore.CAP.Internal.Bootstrapper.BootstrapCoreAsync()
info: DotNetCore.CAP.Processor.CapProcessingServer[0]
      Starting the processing server.
info: DotNetCore.CAP.Internal.Bootstrapper[0]
      ### CAP started!
```

**Comment by xiangxiren** [comment]
The value of `ConsumerThreadCount`and `ProducerThreadCount` must be greater than 0.

**Comment by yang-xiaodong** [comment]
Hello, this is a potential problem, but this is too obvious an error that we do not intend to verify it.
