### ISSUE TITLE
Mysql获取不到链接字符串

### ISSUE THREAD

**Issue by CAH-FlyChen** [dotnetcore/CAP#103]
我需要从config中读取mysql配置文件，但加入后，执行到app.UseCap出现异常。

用如下配置

                services.AddDbContext<EvolutionDBContext>(ServiceLifetime.Transient);
                services.AddCap(x =>
                {
                    x.UseMySql(opt => {
                        opt.ConnectionString = GetDbConnectionStr(Configuration, DataBase);
                    });
                    x.UseEntityFramework<EvolutionDBContext>();
                    x.UseRabbitMQ(v =>
                    {
                        v.HostName = Configuration["RabbitMQ:HostName"];
                        v.UserName = Configuration["RabbitMQ:UserName"];
                        v.Password = Configuration["RabbitMQ:Password"];
                    });

                });

[2018-03-29 19:08:41.0939] FATAL Microsoft.AspNetCore.Hosting.Internal.WebHost: Application startup exception
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at DotNetCore.CAP.MySqlCapOptionsExtension.<>c__DisplayClass3_0.<AddSingletionMySqlOptions>b__0(IServiceProvider x)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.AppBuilderExtensions.UseCap(IApplicationBuilder app)
   at Evolution.Web.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime) in C:\Code\BinChiReposGitolite\EvolutionFramework\Evolution.Web.API\Startup.cs:line 326

**Comment by CAH-FlyChen** [comment]
没用Cap之前是这样使用的
                services.AddEntityFrameworkMySql()
                .AddDbContext<EvolutionDBContext>(options =>
                {
                    options.UseMySql(GetDbConnectionStr(Configuration, DataBase));
                },ServiceLifetime.Transient);

**Comment by CAH-FlyChen** [comment]
经过调试出现在这句话
var bootstrapper = provider.GetRequiredService<IBootstrapper>();

**Comment by yuleyule66** [comment]
![image](https://user-images.githubusercontent.com/8205994/38090554-8f48baf6-3395-11e8-9580-d4132a65f03e.png)

**Comment by CAH-FlyChen** [comment]
但我需要自定义load mysql的连接字符串。

**Comment by CAH-FlyChen** [comment]
services.AddEntityFrameworkMySql()
                .AddDbContext<EvolutionDBContext>(options =>
                {
                    options.UseMySql(GetDbConnectionStr(Configuration, DataBase));
                }, ServiceLifetime.Transient);

                services.AddCap(x =>
                {
                    x.UseEntityFramework<EvolutionDBContext>();
                    x.UseRabbitMQ(v =>
                    {
                        v.HostName = Configuration["RabbitMQ:HostName"];
                        v.UserName = Configuration["RabbitMQ:UserName"];
                        v.Password = Configuration["RabbitMQ:Password"];
                    });

                });

换成上面代码后出现mysql异常

                services.AddEntityFrameworkMySql()
                .AddDbContext<EvolutionDBContext>(options =>
                {
                    options.UseMySql(GetDbConnectionStr(Configuration, DataBase));
                }, ServiceLifetime.Transient);

                services.AddCap(x =>
                {
                    x.UseEntityFramework<EvolutionDBContext>();
                    x.UseRabbitMQ(v =>
                    {
                        v.HostName = Configuration["RabbitMQ:HostName"];
                        v.UserName = Configuration["RabbitMQ:UserName"];
                        v.Password = Configuration["RabbitMQ:Password"];
                    });

                });

不知道是不是mysql问题。但我没使用cap之前，只用
services.AddEntityFrameworkMySql()
.AddDbContext(options =>
{
options.UseMySql(GetDbConnectionStr(Configuration, DataBase));
},ServiceLifetime.Transient);
是没有问题的

**Comment by CAH-FlyChen** [comment]
问题找到了。是mysqlconnector的问题。
