### ISSUE TITLE
aliyun kafka group authorization failed exception

### ISSUE THREAD

**Issue by dazhu6666** [dotnetcore/CAP#1032]
使用阿里云的kafka出现

如下报错

 DotNetCore.CAP.Internal.ConsumerRegister[0]
      Broker: Group authorization failed
      Confluent.Kafka.ConsumeException: Broker: Group authorization failed
         at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
         at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
         at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
         at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass18_1.<Execute>b__2()
2021-11-02 13:41:57.6424|ERROR|DotNetCore.CAP.Internal.ConsumerRegister|Broker: Group authorization failed

在
docker下的kafka则没有问题
groupName已指定

**Comment by dazhu6666** [comment]
阿里云的kafka不能用  .  这个字符

长度限制为 3 ~ 64 个字符，只能包含英文、数字、短横线（-）以及下划线（_），且至少包含一个英文或数字

**Comment by dazhu6666** [comment]
阿里云的kafka不能用  .  这个字符

长度限制为 3 ~ 64 个字符，只能包含英文、数字、短横线（-）以及下划线（_），且至少包含一个英文或数字

**Comment by yang-xiaodong** [comment]
We are unable to assist with environmental issues. From the perspective of the exception, the exception is caused by uthorization failed
