### ISSUE TITLE
 An exception occurred while executing the subscription method 

### ISSUE THREAD

**Issue by slagumen** [dotnetcore/CAP#1062]
Hi, we are encountering this issue below. Need assistance please see the logs below

[08:31:31 ERR] An exception occurred while executing the subscription method. Topic:SignalRNotificationEvent, Id:1472826512778276864
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Cannot send to an empty group name. ---> System.InvalidOperationException: Cannot send to an empty group name.
   at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.SendGroupsAsync(IReadOnlyList`1 groupNames, String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Internal.MultipleGroupProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(IClientProxy clientProxy, String method, Object arg1, Object arg2, CancellationToken cancellationToken)
   at Cnx.Notification.API.Domain.Events.NotificationEventHandler.Handle(SignalRNotificationEvent signalRNotificationEvent) in /src/Services/Notification/Cnx.Notification.API/Domain/Events/NotificationEventHandler.cs:line 56
   at lambda_method(Closure , Object )
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, String parameterString)
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.InvokeAsync(ConsumerContext context)
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage)
   at DotNetCore.CAP.DefaultSubscriberExecutor.ExecuteWithoutRetryAsync(CapReceivedMessage message)
   
   Thanks

**Comment by yang-xiaodong** [comment]
How should I help you?  this is the exception thrown by your subscription method
