### ISSUE TITLE
How to consume from heterogeneous systems for kafka?

### ISSUE THREAD

**Issue by linnspace** [dotnetcore/CAP#1066]
when i use producer to produce msg and consumer to consume msg,it's work very well under the cap control。
the storage is `mysql` and message queue is `kafka`。
and  now i have a question，which is my code is only to consume msg under cap framework，the producer is not  c# code under cap framework。

it's a c++ language implement‘s  kafka client。

can i use this consume code and third-party `kafka` producer client meanwhile?
i read the cap doc and issue，i find some situation like this。but  i can't understand what it says！the kafka client publish msg to kafka without write msg to mysql `cap published` table。how cap can handle the `cap-received` table?  because published and received is a one to one relation。

consume demo like that
```
{
    [ApiController]
    [Route("[controller]")]
    public class MessageGetController : Controller
    {
        private int num = 0;
        private readonly ICapPublisher _capPublisher;
        public MessageGetController(ICapPublisher capPublisher)
        {
            _capPublisher = capPublisher;
        }
        
        public IActionResult Index()
        {
            return Ok("test!");
        }
        
        
        [NonAction]
        [CapSubscribe("topic1")]
        public async Task GetDate2(string dt)
        {
            Console.WriteLine($"NUM{num}:{dt}");
            num++;
        }
    }
}
```
thanks very much！

**Comment by yang-xiaodong** [comment]
> can i use this consume code and third-party kafka producer client meanwhile?

Yes, you can receive messages directly from kafka, you can check [here](https://cap.dotnetcore.xyz/user-guide/en/transport/kafka/#customheaders-options) to know how to integrate from heterogeneous systems

**Comment by linnspace** [comment]
yes,if i send msg to kafka with console tools rather than c# code under cap framework, there is an error like this!
As your mentioned above,what the outbox mode means? the answer can find in cap docs? 
```
DotNetCore.CAP.Internal.ConsumerRegister[0]
      An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
MySqlConnector.MySqlException (0x80004005): Column 'Name' cannot be null
 ---> MySqlConnector.MySqlException (0x80004005): Column 'Name' cannot be null
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySqlDataReader.cs:line 129
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 422
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 61
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 263
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 100
   at DotNetCore.CAP.MySql.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.MySql.MySqlDataStorage.StoreReceivedMessage(Object[] sqlParams)
   at DotNetCore.CAP.MySql.MySqlDataStorage.StoreReceivedExceptionMessage(String name, String group, String content)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_0.<<RegisterMessageProcessor>b__0>d.MoveNext()
```

**Comment by yang-xiaodong** [comment]
Message Id and Name are required in the header
https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

**Comment by linnspace** [comment]
> Message Id and Name are required in the header https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

i seem know what you mean, if third message queue client add msgid and topic name in message queue header,it's will  also work well。
