### ISSUE TITLE
 Execution Timeout Expired + the message is still sent

### ISSUE THREAD

**Issue by NikitaEgorov** [dotnetcore/CAP#1076]

**Comment by NikitaEgorov** [comment]
**First one timeout exception**

```csparp
[11:22:51 ERR] An exception occurred when sending a message to the MQ. Id:1486253022964764672
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
Operation cancelled by user.
The statement has been terminated.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameter
EncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String m
ethod)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.ChangeMessageStateAsync(String tableName, MediumMessage message, StatusName state)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.ChangeMessageStateAsync(String tableName, MediumMessage message, StatusName state)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.ChangePublishStateAsync(MediumMessage message, StatusName state)
   at DotNetCore.CAP.Internal.MessageSender.SetSuccessfulState(MediumMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendWithoutRetryAsync(MediumMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendAsync(MediumMessage message)
   at DotNetCore.CAP.Processor.Dispatcher.Sending(CancellationToken cancellationToken)
ClientConnectionId:72b07602-1570-42ff-abe6-b1e2c7385a21
Error Number:-2,State:0,Class:11
[11:22:51 DBG] Received message. id:1486253023191257088, name: AgreementChangedIntegrationEvent
```

**Second issue**

I have UnitOfWork in my application. And when I do `transaction.Commit()` it takes a long time. The CAP starts sending an event to the transport, but if I stop the application, it has already sent the CAP event, but the data in the SQLServer database is not saved :)

**Comment by NikitaEgorov** [comment]
![image](https://user-images.githubusercontent.com/10349650/151134157-25593f9b-8e35-4f6d-9abd-bd55914e4ad5.png)

**Comment by NikitaEgorov** [comment]
I REPRODUCE 100%♥♥♥♥♥♥♥♥♥♥♥♥

```csharp

[Route("~/adonet/transaction")]
public async Task<IActionResult> AdonetWithTransaction()
{
    using (var scope = new TransactionScope(TransactionScopeOption.Required,
               new TransactionOptions {IsolationLevel = IsolationLevel.Serializable}))
    {
        using (var connection = new SqlConnection(ConnectionString))
        {
            using (var transaction = connection.BeginTransaction(_capBus, false))
            {
                //your business code
                var longtext = new string('z', 1800);
                for (int i = 0; i < 50000; i++)
                {
                    connection.Execute($"insert into test(name) values('{longtext}')", transaction: transaction);

                    if (i % 1000 == 0)
                    {
                        Console.WriteLine(i);
                    }

                    _capBus.Publish("sample.rabbitmq.sqlserver", new Person
                    {
                        Id = 123,
                        Name = "Bar" + i
                    });

                    connection.Execute($"insert into test(name) values('{longtext}')", transaction: transaction);
                }

                Console.WriteLine($@"{DateTime.Now} BEGIN COMMIT");
                transaction.Commit();

                Console.WriteLine($@"{DateTime.Now} END COMMIT");
                scope.Complete();
            }
        }
    }

    return Ok();
}

```

**Comment by yang-xiaodong** [comment]
Can it be reproduced without using `TransactionScope`?

**Comment by NikitaEgorov** [comment]
No.
TransactionScope is the main thing for reproduce

**Comment by yang-xiaodong** [comment]
This is out of our control and we don't provide support for TransactionScope because MSDTC is required to use TransactionScope in a distributed environment and CAP aims to get away from MSDTC

**Comment by NikitaEgorov** [comment]
I have disabled MSDTC
