### ISSUE TITLE
Can not receive the message published from Power Platform

### ISSUE THREAD

**Issue by yiliu-tc** [dotnetcore/CAP#1088]
Want to receive some messages published from Power Platform side, and get following error, while power platform side can successfully receive the message published from CAP side:

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.MatchUsingName(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.SelectBestCandidate(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.MethodMatcherCache.TryGetTopicExecutor(String topicName, String groupName, ConsumerExecutorDescriptor& matchTopic)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass22_0.<RegisterMessageProcessor>b__0(Object sender, TransportMessage transportMessage)
202

**Comment by yang-xiaodong** [comment]
How to reproduce?

**Comment by yang-xiaodong** [comment]
No response, closed

**Comment by yiliu-tc** [comment]
Sorry for late response, public holiday here.

To reproduce the issue, we have third party power apps publish event to service bus, and we have .NET Core App to subscribe the event on other end, as the event published from power apps do not contain those CAP message headers like cap-msg-name, the CAP lib throws exceptions and service bus moving the msg to dead letter queue.

**Comment by yang-xiaodong** [comment]
please see: https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#custom-headers

**Comment by yiliu-tc** [comment]
oh, thanks so much for this. it worked perfectly.
