### ISSUE TITLE
正常运行一段时间，RabbitMQ突发异常且不能恢复

### ISSUE THREAD

**Issue by hello-ldf** [dotnetcore/CAP#1166]
我们这有一个服务，分布式部署，三个实例，三个实例都会发布消息。
目前碰到的问题是，每隔一段时间，系统就会抛出下列异常，而且异常一旦出现，该实例就会一直抛出该异常，同时间的其他实例却是正常的。然后重启该实例，就不会抛出该异常了。
想请教一下可能造成问题的原因和我能尝试做的方法。

这是昨天异常出现的日志情况

期间大致每隔三分钟出现一次以下异常
2022-06-28 18:09:07.557 [ERR]An exception occured while publishing a message, reason:Failed : . message id:2172233399910963448  [DotNetCore.CAP.Processor.Dispatcher. at :]
DotNetCore.CAP.Internal.PublisherSentFailedException: Timed out waiting for acks
 ---> System.IO.IOException: Timed out waiting for acks
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie(TimeSpan timeout)
   at RabbitMQ.Client.Impl.AutorecoveringModel.WaitForConfirmsOrDie(TimeSpan timeout)
   at DotNetCore.CAP.RabbitMQ.RabbitMQTransport.SendAsync(TransportMessage message)
   --- End of inner exception stack trace ---

期间不间断出现 RabbitMQ channel model create failed 
18:11:36->18:38:52->18:42:39->18:45:32->18:49:17->18:56:21->19:05:22->19:05:44->19:26:16->20:30:41->20:50:28

2022-06-28 18:11:36.626 [ERR]RabbitMQ channel model create failed!  [DotNetCore.CAP.RabbitMQ.ConnectionChannelPool. at :]
System.TimeoutException: The operation has timed out.
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateNonRecoveringModel()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.Rent()

期间高频出现以下异常
DotNetCore.CAP.Internal.PublisherSentFailedException: Pipelining of requests forbidden
 ---> System.NotSupportedException: Pipelining of requests forbidden
   at RabbitMQ.Client.Impl.RpcContinuationQueue.Enqueue(IRpcContinuation k)
   at RabbitMQ.Client.Impl.ModelBase.Enqueue(IRpcContinuation k)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ConfirmSelect(Boolean nowait)
   at DotNetCore.CAP.RabbitMQ.RabbitMQTransport.SendAsync(TransportMessage message)
   --- End of inner exception stack trace ---

**Comment by yang-xiaodong** [comment]
It's unusual to get this error; when physically closing a channel (rather than returning it to the cache), the framework calls `WaitForConfirmsOrDie` to make sure any pending confirms are received. The fact that it is throwing an exception means the confirm was not received for some reason. 

Generally this has nothing to do with CAP, refer to the content to find the answer.

https://groups.google.com/g/rabbitmq-users/search?q=WaitForConfirmsOrDie%20
https://www.cnblogs.com/guanxiaohe/p/16185128.html

**Comment by hello-ldf** [comment]
thx
