### ISSUE TITLE
I got a lot of messaged Scheduled in the table received

### ISSUE THREAD

**Issue by louieyu** [dotnetcore/CAP#1214]
![QQ截图20220927003029](https://user-images.githubusercontent.com/21114653/192332261-4a12f3d6-60d8-491a-a41c-109dd662bd43.png)
I don't know what caused it, is the data stored in the Received table not related to the rabbitmq queue?

**Comment by yang-xiaodong** [comment]
Please show the success message subscriber execution time log.

Such as
```
info: DotNetCore.CAP.Internal.SubscribeDispatcher[0]
    Executed subscriber method 'xxx' on group 'xxx' in xxx ms
```

**Comment by louieyu** [comment]
I only record the log on the error level .

*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:45:22,432
线程ID：34
日志等级：ERROR
日志类型：DotNetCore.CAP.Internal.SubscribeDispatcher
An exception occurred while executing the subscription method. Topic:OrderSyncEvent, Id:1574359502117289984
*——*——*——*——*——*——E n d——*——*——*——*——*——*
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LH.Service.IntegrationEvents.EventHandlers.ErpSync.OrderSyncEventHandler.Handler(OrderSyncEvent event) in D:\gitee\lhwebapi\src\LH.Service\IntegrationEvents\EventHandlers\ErpSync\OrderSyncEventHandler.cs:line 108
   at lambda_method(Closure , Object )
   at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.ExecuteWithoutRetryAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:46:47,547
线程ID：144
日志等级：ERROR
日志类型：LH.Service.IntegrationEvents.EventHandlers.CustomSync.QuoteResultSyncEventHandler
The orderNo 4924837986517 has no query data
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:48:04,000
线程ID：144
日志等级：INFO 
日志类型：LH.JobServices.Jobs.LhRightGiveJob
LhRightGiveJob,2022/9/26 21:48:04,
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:48:36,811
线程ID：144
日志等级：ERROR
日志类型：LH.Service.IntegrationEvents.EventHandlers.CustomSync.QuoteResultSyncEventHandler
The orderNo 4924170404053 has no query data
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:51:04,026
线程ID：115
日志等级：INFO 
日志类型：LH.JobServices.Jobs.LhRightGiveJob
LhRightGiveJob,2022/9/26 21:51:04,
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:52:34,706
线程ID：146
日志等级：ERROR
日志类型：LH.Service.SumaiApi.SumaiHttpClient
订单号：4838261260448,StatusCode:OK,{"HasError":true,"ErrorCode":null,"Message":"已经存在，不再同步","ResultObject":null,"ResultShelfObject":null,"MapData":{}}
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:52:34,709
线程ID：146
日志等级：ERROR
日志类型：LH.Service.IntegrationEvents.EventHandlers.ErpSync.OrderSyncEventHandler
Object reference not set to an instance of an object.
*——*——*——*——*——*——E n d——*——*——*——*——*——*
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2022-09-26 21:52:34,710
线程ID：146
日志等级：ERROR
日志类型：DotNetCore.CAP.Internal.SubscribeDispatcher
An exception occurred while executing the subscription method. Topic:OrderSyncEvent, Id:1574345445091983360
*——*——*——*——*——*——E n d——*——*——*——*——*——*
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LH.Service.IntegrationEvents.EventHandlers.ErpSync.OrderSyncEventHandler.Handler(OrderSyncEvent event) in D:\gitee\lhwebapi\src\LH.Service\IntegrationEvents\EventHandlers\ErpSync\OrderSyncEventHandler.cs:line 108
   at lambda_method(Closure , Object )
   at DotNetCore.CAP.Internal.SubscribeInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, Object[] parameter)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.ExecuteWithoutRetryAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
*——*——*——*——*——*——Begin——*——*——*——*——*——*

**Comment by yang-xiaodong** [comment]
You need to provide more information so that we know your consumer execution time

**Comment by yang-xiaodong** [comment]
No response, closed!
