### ISSUE TITLE
The given key 'cap-msg-id' was not present in the dictionary

### ISSUE THREAD

**Issue by Guram-K** [dotnetcore/CAP#1229]
I'm getting an error on startup in brand new .net 6 project,
```
fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
      The given key 'cap-msg-id' was not present in the dictionary.
      System.Collections.Generic.KeyNotFoundException: The given key 'cap-msg-id' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at DotNetCore.CAP.Messages.TransportMessage.GetId()
         at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass22_0.<RegisterMessageProcessor>b__0(Object sender, TransportMessage transportMessage)
         at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
         at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass18_1.<Execute>b__2()
```

service registration looks like this:

```
builder.Services.AddTransient<INotificationIntegrationEventHandler, NotificationIntegrationEventHandler>();

builder.Services.AddCap(x =>
{
    x.UseEntityFramework<IntegrationEventDbContext>();
    x.UseKafka("localhost:9092");
    x.DefaultGroupName = "default.consumer.group";
});
```

The subscriber:
```
public class NotificationIntegrationEventHandler: INotificationIntegrationEventHandler, ICapSubscribe
{
    [CapSubscribe(Topics.Notifications)]
    public async Task HandleMessage(string message, CancellationToken cancellationToken)
    {
        Console.WriteLine($"Handling the message: {message}");
    }
}
```

**Comment by pheu** [comment]
@Guram-K How did you resolve it? I'm getting this exception even in the Demo project.
