### ISSUE TITLE
Get messages of type 'MediumMessage' failed. Retrying

### ISSUE THREAD

**Issue by JontyMin** [dotnetcore/CAP#1241]
hello, I am using CAP in aspnetboilerplate framework version 6.4.0
as follows
```xml
    <!-- CAP -->
    <PackageReference Include="DotNetCore.CAP" Version="5.2.0" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="5.2.0" />
    <PackageReference Include="DotNetCore.CAP.SqlServer" Version="5.2.0" />
```
and Before AddAbp()
```csharp
services.AddCap(opt =>
            {
                var conn = Configuration.ConnectionStringsDefault();
                opt.UseSqlServer(conn);

                opt.UseRabbitMQ(x =>
                {
                    x.HostName = "localhost";
                    x.UserName = "admin";
                    x.Password = "123456"
                });
            });
```
When I use the same connection string as EFCore, I get a warning

```txt
warn: DotNetCore.CAP.Processor.MessageNeedToRetryProcessor[1]
      Get messages of type 'MediumMessage' failed. Retrying...
      Microsoft.Data.SqlClient.SqlException (0x80131904): You can only specify the READPAST lock in the READ COMMITTED or REPEATABLE READ isolation levels.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.Read()
         at DotNetCore.CAP.SqlServer.SqlServerDataStorage.<GetMessagesOfNeedRetryAsync>b__18_0(IDataReader reader)
         at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteReader[T](IDbConnection connection, String sql, Func`2 readerFunc, Object[] sqlParams)
         at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetMessagesOfNeedRetryAsync(String tableName)
         at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetMessagesOfNeedRetryAsync(String tableName)
         at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetPublishedMessagesOfNeedRetry()
         at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
      ClientConnectionId:8ef3d14d-ee0d-4da3-8732-58a6b47d5c7c
      Error Number:650,State:1,Class:16
```
If it does not match, as follows, it works fine

```txt
    "Default": "Server=localhost; Database=cap_test_db; User ID=sa;Password=bb123456??;MultipleActiveResultSets=True",
    "CAP": "Server=localhost; Database=cap_test_db; User ID=sa;Password=bb123456??"
```
get CAP connection string
```csharp
               var conn = Configuration.GetConnectionString("CAP");
                opt.UseSqlServer(conn);
```
Why, please?

**Comment by JontyMin** [comment]
OK  Only the transaction isolation level needs to be set to ReadCommitted

```csharp
 Configuration.UnitOfWork.IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted;
```
