### ISSUE TITLE
Exception thrown when terminate the program with Ctrl+C 

### ISSUE THREAD

**Issue by yuleyule66** [dotnetcore/CAP#130]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug

- Which version of CAP, OS and .NET Core?
CAP version : 2.2.2

- What happen?

When terminate the program with Ctrl+C, the following exception is thrown.

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Processor.CapProcessingServer.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at SkyWalking.Sample.Cap.Producer.Program.Main(String[] args) in F:\skywalking-netcore\sample\SkyWalking.Sample.Cap.Producer\Program.cs:line 10
```

**Comment by yuleyule66** [comment]
fixed in version 2.2.3
