### ISSUE TITLE
CAP的必要初始化阻塞Host启动是否会更好

### ISSUE THREAD

**Issue by stratosblue** [dotnetcore/CAP#1315]
现在CAP的初始化是在`BackgroundService`中异步执行的，当调用 `IHost.StartAsync()` 之后未等待初始化完成就立即返回了，在某些极端情况下会出现消费者还未注册完成就进行了消息发送，导致该消息的丢失，一个典型的应用场景是使用 `InMemoryMessageQueue` 进行相关的单元测试，该情况导致单元测试无法按预期执行。

这里提供一个简单的 [复现代码](https://github.com/dotnetcore/CAP/files/11241110/TestProject1.zip)：
```C#
[TestClass]
public class UnitTest1
{
    protected IHost TestHost { get; private set; } = null!;
    
    private async Task Run()
    {
        await TestHost.Services.GetRequiredService<ICapPublisher>().PublishAsync("test.subscribe", DateTime.UtcNow);
        var testSubscribe = TestHost.Services.GetRequiredService<TestSubscribe>();
        await testSubscribe.TaskCompletionSource.Task.WaitAsync(TimeSpan.FromSeconds(5));
    }

    [TestMethod]
    public Task TestMethod1() => Run();

    [TestMethod]
    public Task TestMethod2() => Run();
    
    [TestMethod]
    public Task TestMethod3() => Run();
    
    [TestMethod]
    public Task TestMethod4() => Run();
    
    [TestMethod]
    public Task TestMethod5() => Run();

    [TestCleanup]
    public virtual async Task CleanupTestAsync()
    {
        await TestHost.StopAsync();
        TestHost.Dispose();
        TestHost = null!;
    }

    [TestInitialize]
    public virtual async Task InitializeTest()
    {
        var builder = Host.CreateDefaultBuilder()
                          .ConfigureLogging(builder =>
                          {
                              builder.ClearProviders();
                              builder.AddSimpleConsole();
                              builder.SetMinimumLevel(LogLevel.Trace);
                          })
                          .ConfigureServices(services =>
                          {
                              services.AddCap(x =>
                              {
                                  x.UseInMemoryStorage();
                                  x.UseInMemoryMessageQueue();
                              });

                              services.AddSingleton<TestSubscribe>();
                          });
        TestHost = builder.Build();
        await TestHost.StartAsync();
    }
}

class TestSubscribe : ICapSubscribe
{
    public TaskCompletionSource TaskCompletionSource { get; } = new();

    [CapSubscribe("test.subscribe")]
    public void MethodName(DateTime dateTime)
    {
        TaskCompletionSource.SetResult();
    }
}
```

执行 `dotnet test` ，可能会有多次执行超时的情况，结果示例如下：
```log
失败!  - 失败:     4，通过:     1，已跳过:     0，总计:     5，持续时间: 21 s - TestProject1.dll (net6.0)
```
检查失败的测试输出日志，可以看到失败原因是消息发送时消费者还未注册
```log
  失败 TestMethod5 [5 s]
  错误消息:
   Test method TestProject1.UnitTest1.TestMethod5 threw exception:
System.TimeoutException: The operation has timed out.
  堆栈跟踪:
      at TestProject1.UnitTest1.Run() in D:\TestProject1\TestProject1\UnitTest1.cs:line 18
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

  标准输出消息:
 dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
       Hosting starting
 dbug: DotNetCore.CAP.Internal.Bootstrapper[0]
       ### CAP background task is starting.
 info: Microsoft.Hosting.Lifetime[0]
       Application started. Press Ctrl+C to shut down.
 info: Microsoft.Hosting.Lifetime[0]
       Hosting environment: Production
 info: Microsoft.Hosting.Lifetime[0]
       Content root path: D:\TestProject1\TestProject1\bin\Debug\net6.0
 dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
       Hosting started
 info: DotNetCore.CAP.Processor.Dispatcher[0]
       Starting default Dispatcher
 dbug: Savorboard.CAP.InMemoryMessageQueue.InMemoryMqTransport[0]
       Event message [test.subscribe] has been published.
 info: DotNetCore.CAP.Processor.CapProcessingServer[0]
       Starting the processing server.
 info: Savorboard.CAP.InMemoryMessageQueue.InMemoryConsumerClient[0]
       InMemory message queue initialize the topic: cap.queue.testhost.v1 test.subscribe
 dbug: DotNetCore.CAP.Processor.TransportCheckProcessor[0]
       Transport connection checking...
 dbug: DotNetCore.CAP.Processor.TransportCheckProcessor[0]
       Transport connection healthy!
 dbug: DotNetCore.CAP.Processor.CollectorProcessor[0]
       Collecting expired data from table: PublishedMessages
 dbug: DotNetCore.CAP.Processor.CollectorProcessor[0]
       Collecting expired data from table: ReceivedMessages
 info: DotNetCore.CAP.Internal.Bootstrapper[0]
       ### CAP started!
 dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
       Hosting stopping
```

初始化阻塞 `Host` 启动可能会导致Host启动时间变长，如果不可接受，那么还可以：
- 提供一个相关的可配置项，仅当配置该项时阻塞启动
- 提供一个检查方法，可以手动检查是否初始化完成

**Comment by yang-xiaodong** [comment]
I think your app should have health checks and only serve when it ready

**Comment by stratosblue** [comment]
> I think your app should have health checks and only serve when it ready

I think you are right. And is there any way to make sure that CAP is ready to consume message.

**Comment by yang-xiaodong** [comment]
消费和发送是分开的，互不影响，消息队列会持久化消息。
InMemoryQueue只是用于测试，并非生产环境，你可以单独使用CAP在UT中。

```cs

    protected IServiceProvider _provider;
    private CancellationTokenSource _cts = new CancellationTokenSource(3000);

    [TestMethod]
    public Task TestMethod1() => Run();

    private async Task Run()
    {
        await _provider.GetRequiredService<ICapPublisher>().PublishAsync("test.subscribe", DateTime.UtcNow);
        var testSubscribe = _provider.GetRequiredService<TestSubscribe>();
        await testSubscribe.TaskCompletionSource.Task.WaitAsync(TimeSpan.FromSeconds(5));
    }

    [TestInitialize]
    public virtual async Task InitializeTest()
    {
        IServiceCollection sc = new ServiceCollection();
        sc.AddSingleton<TestSubscribe>();
        sc.AddLogging();
        sc.AddCap(x =>
        {
            x.UseInMemoryStorage();
            x.UseInMemoryMessageQueue();
        });
        _provider = sc.BuildServiceProvider();
        await _provider.GetRequiredService<IBootstrapper>().BootstrapAsync(_cts.Token);
    }
```

**Comment by stratosblue** [comment]
好的，感谢，了解了
