### ISSUE TITLE
Azure Service Bus, consumer fails if subscription has session enabled

### ISSUE THREAD

**Issue by demorgi** [dotnetcore/CAP#1397]
Having both producer and consumer using CAP on top of Azure Service Bus, both of them having sessions enabled. This causes exceptions on consumer side

```
 - Exception: System.InvalidOperationException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:<private>, SystemTracker:<private>
 For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__41_0>d.MoveNext()
 --- End of stack trace from previous location ---
 at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
 at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, CancellationToken cancellationToken)
 at Azure.Messaging.ServiceBus.ServiceBusReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, Boolean isProcessor, CancellationToken cancellationToken)
 at Azure.Messaging.ServiceBus.ReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken cancellationToken)
```
This is happening because of consumer side misconfiguration, for more context please see
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md#sending-and-receiving-session-messages

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample05_SessionProcessor.md

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L319
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusSessionProcessor.cs#L109C1-L109C22

To reproduce this issue
1. Create a new topic in azure service bus
2. Add new CAP consumer (2 subscription methods, same group name)
3. Set EnableSessions = true in CAP configuration

Expected result
1. New subscription is created with enabled sessions
2. Subscriber can ingest messages

Actual result
1. New subscription is created with enabled sessions
2. Subscriber in unable to ingest messages, see error above

**Comment by yang-xiaodong** [comment]
Fixed in version 7.2.2
