### ISSUE TITLE
docker + netcore2.1 ，Dashboard 无法打开

### ISSUE THREAD

**Issue by imcc** [dotnetcore/CAP#140]
### Bug

- Which version of CAP, OS and .NET Core?
  - 操作系统：CentOS 7.2
  - 部署方式：docker
  - CAP 版本： 2.2.2 和 2.2.4 
  - .Net版本：netcore2.1 (2.1.300)

- What happen?

打开 Dashboard 时报500错误，异常信息如下：

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLEC92UDC35E", Request id "0HLEC92UDC35E:00000001": An unhandled exception was thrown by the application.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at DotNetCore.CAP.Infrastructure.Helper.GetIpNum(String ipAddress)
   at DotNetCore.CAP.Infrastructure.Helper.IsInnerIP(String ipAddress)
   at DotNetCore.CAP.Dashboard.LocalRequestsOnlyAuthorizationFilter.Authorize(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.<>c__DisplayClass5_0.<Invoke>b__0(IDashboardAuthorizationFilter filter)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Abp.AspNetCore.Security.AbpSecurityHeadersMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

备注：目前发现只会在 netcore2.1+docker 出现。开发环境是 macOS+netcore2.1，没有出现过这个错误。 退回到 netcore2.0 则一切正常。

**Comment by imcc** [comment]
即使在部署的机器上 wget 127.0.0.1:port/cap，依然是这个错误。说明 context.Request.RemoteIpAddress 不对。

**Comment by yuleyule66** [comment]
.net core 2.1 针对RemoteIpAddress的获取做了一些改动，这应该是一个新bug，谢谢反馈。

**Comment by yuleyule66** [comment]
Fixed in version `2.2.5-preview-45139132`

**Comment by imcc** [comment]
thanks
