### ISSUE TITLE
Error starting processors. The CancellationTokenSource has been disposed.

### ISSUE THREAD

**Issue by davidhenley** [dotnetcore/CAP#1411]
This just started happening today and I don't understand what this error means. 

```
[10:28:03 INF] Starting default Dispatcher
[10:28:03 INF] Shutting down the processing server...
[10:28:03 INF] ### CAP shutdown!
[10:28:03 ERR] Starting the processors throw an exception.
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.get_Token()
   at DotNetCore.CAP.Internal.ConsumerRegister.Execute()
   at DotNetCore.CAP.Internal.ConsumerRegister.Start(CancellationToken stoppingToken)
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapCoreAsync()
[10:28:03 ERR] Starting the processors throw an exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapCoreAsync()
[10:28:03 ERR] Starting the processors throw an exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapCoreAsync()
```

```cs
services.AddCap(x =>
        {
            x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
            x.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
            x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
            x.JsonSerializerOptions.Converters.Add(new MvcExtensions.DateTimeConverter());

            x.UseEntityFramework<DbContext>(o => { o.Schema = "Events"; });

            x.UseAzureServiceBus(o =>
            {
                o.ConnectionString = configuration.GetConnectionString("ServiceBus")!;
                o.TopicPath = configuration["ServiceBusTopicName"]!;
                o.AutoCompleteMessages = false;
                o.CustomHeaders = message => new List<KeyValuePair<string, string>>
                {
                    new(DotNetCore.CAP.Messages.Headers.MessageId, SnowflakeId.Default().NextId().ToString()),
                    new(DotNetCore.CAP.Messages.Headers.MessageName, message.ApplicationProperties["Type"].ToString())
                };
            });
        });
```

**Comment by yang-xiaodong** [comment]
It's hard to say what causes this, the best thing you can use source code to run our example and reproduce the process
