### ISSUE TITLE
 SQL Server replication readpast error!  "You can only specify the READPAST lock in the READ COMMITTED or REPEATABLE READ isolation levels"

### ISSUE THREAD

**Issue by syond0915** [dotnetcore/CAP#1543]
Category: DotNetCore.CAP.Processor.MessageNeedToRetryProcessor
EventId: 1

Get messages from storage failed. Retrying...

Exception: 
Microsoft.Data.SqlClient.SqlException (0x80131904): You can only specify the READPAST lock in the READ COMMITTED or REPEATABLE READ isolation levels.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.<GetMessagesOfNeedRetryAsync>b__18_0(IDataReader reader)
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteReader[T](IDbConnection connection, String sql, Func`2 readerFunc, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetMessagesOfNeedRetryAsync(String tableName)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetMessagesOfNeedRetryAsync(String tableName)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.GetReceivedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
ClientConnectionId:d6aabc8d-5ddb-4adb-944c-602301eee7c8
Error Number:650,State:1,Class:16

![image](https://github.com/dotnetcore/CAP/assets/37108266/3ce50b1c-9daa-4492-a0e5-bc507fc04fe0)

**Comment by carlosxjose** [comment]
@syond0915 it looks like you are working with a SQL Server replicarion scenario ???

If so did you exclude the caps databases?

**Comment by yang-xiaodong** [comment]
> @syond0915 it looks like you are working with a SQL Server replication scenario ???
> 
> If so did you exclude the caps databases?

Thanks @carlosxjose for the answer.  Yes, he is using SQL Server replication.

**Comment by syond0915** [comment]
Warning still alive, how should I handle it？
