### ISSUE TITLE
项目运行一段时间发生以下错误日志

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#233]
`
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50] Using an in-memory repository. Keys will not be persisted to storage.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35] No XML encryptor configured. Key {e7a2fab4-0576-41be-9c2c-b1d0531ea736} may be persisted to storage in unencrypted form.

Hosting environment: Production
Content root path: E:\CheHuoYi-V3-FaBu\CHY.BusinessService\User
Now listening on: http://127.0.0.1:1840
Application started. Press Ctrl+C to shut down.

warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1] Processor 'DotNetCore.CAP.SqlServer.SqlServerCollectProcessor' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - 信号灯超时时间已到) ---> System.ComponentModel.Win32Exception (121): 信号灯超时时间已到
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at DotNetCore.CAP.SqlServer.SqlServerCollectProcessor.ProcessAsync(ProcessingContext context)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
ClientConnectionId:0dc1302c-b7c7-4159-9749-326dcd26ebfa
Error Number:121,State:0,Class:20
`

**Comment by bao2314483** [comment]
补充这个项目没有任何数据库连接,只有CAP

**Comment by yang-xiaodong** [comment]
I have not encountered this problem, this should not be the error caused by CAP. 
Maybe you can refer to https://stackoverflow.com/questions/2962927/a-transport-level-error-has-occurred-when-receiving-results-from-the-server

**Comment by bao2314483** [comment]
打开不了网址
