### ISSUE TITLE
同一个请求内多次发布消息出错，提示MySqlConnection已disposed掉

### ISSUE THREAD

**Issue by kulend** [dotnetcore/CAP#25]
RabbitMQ,MySql环境
在同一个请求内两次Publish消息，第二次发送错误。
是bug还是我写的有问题？
 
`            
            //发送消息

            await _eventPublisher.PublishAsync("msg1", new UserLoginEvent {UserId = entity.Id});
            try
            {
                await _eventPublisher.PublishAsync("backend_user_action_log", log);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
`

Exception

`
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlConnection'.
   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed()
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.MySql.CapPublisher.<PublishWithTransAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.MySql.CapPublisher.<PublishCoreAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
`

**Comment by yuleyule66** [comment]
Thanks for your feedback. I will check it later.

**Comment by yuleyule66** [comment]
This occurs because the incorrect dispose of EF connection. I have fixed this bug and I will release a new preview version later.

**Comment by yuleyule66** [comment]
2.0 preview published, the problem has now been solved.

**Comment by ajdwfnhaps** [comment]
我今天使用v2.1.0 遇到同样的问题  我明天把异常信息发布上来 提个issue  
aspnetcore2.0
ef core2.0
quazt.net
autofac
