### ISSUE TITLE
运行期间每天会出现警告日志

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#252]
`warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
Processor 'DotNetCore.CAP.Processor.NeedRetryMessageProcessor' failed. Retrying...
System.InvalidOperationException: Invalid operation. The connection is closed.
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.GetPublishedMessagesOfNeedRetry()
at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessPublishedAsync(IStorageConnection connection, ProcessingContext context)
at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessAsync(ProcessingContext context)
at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
Processor 'DotNetCore.CAP.Processor.NeedRetryMessageProcessor' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error 258
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.GetPublishedMessagesOfNeedRetry()
at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessPublishedAsync(IStorageConnection connection, ProcessingContext context)
at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessAsync(ProcessingContext context)
at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
ClientConnectionId:e7116280-df02-4fff-b910-7a389c255083
Error Number:-2,State:0,Class:11`

每天都会出现一次，之前我也提问过因为sql2008原因，这次我改用了sql2016也同样出现这个问题

**Comment by yang-xiaodong** [comment]
`The connection is closed.  Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding `

似乎是网络问题造成的数据库连接不稳定，这个需要你自己排查下。

我们使用的 MySql，生产环境跑了很长的时间了，没有过遇到类似的问题。
