### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 42703: column "version" does not exist

### ISSUE THREAD

**Issue by ymind** [dotnetcore/CAP#256]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of CAP, OS and .NET Core?
2.4.0+
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
```
Npgsql.PostgresException (0x80004005): 42703: column "version" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1012
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 526
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1215
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at DotNetCore.CAP.PostgreSql.PostgreSqlPublisher.ExecuteAsync(CapPublishedMessage message, ICapTransaction transaction, CancellationToken cancel) in C:\projects\cap\src\DotNetCore.CAP.PostgreSql\ICapPublisher.PostgreSql.cs:line 50
   at DotNetCore.CAP.Abstractions.CapPublisherBase.PublishAsyncInternal(CapPublishedMessage message) in C:\projects\cap\src\DotNetCore.CAP\Abstractions\CapPublisherBase.cs:line 83
   at DotNetCore.CAP.Abstractions.CapPublisherBase.PublishAsync[T](String name, T contentObj, String callbackName, CancellationToken cancellationToken) in C:\projects\cap\src\DotNetCore.CAP\Abstractions\CapPublisherBase.cs:line 64
```

**Comment by yang-xiaodong** [comment]
See release notes
https://github.com/dotnetcore/CAP/releases

**Comment by ymind** [comment]
the error is in `ICapPublisher.PostgreSql.cs`.

```csharp
private string PrepareSql()
{
	return
		$"INSERT INTO ...,\"Version\",...)VALUES(@Id,'{_options.Version}',...);";
}
```
