### ISSUE TITLE
列名 'Version' 无效

### ISSUE THREAD

**Issue by wtujvk** [dotnetcore/CAP#282]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of CAP, OS and .NET Core?
netcoreapp2.0, DotNetCore.CAP.RabbitMQ2.4.2 ，DotNetCore.CAP.SqlServer2.4.2
- Which company or project?
CAP
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
列名 'Version' 无效

 _capBus.Publish(”ddd.lcn“, message);
Details:
2019-01-30 17:58:28.4193|CAP.Web.Controllers.HomeController|ERROR|System.Data.SqlClient.SqlException (0x80131904): 列名 'Version' 无效。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__39.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.SqlServer.SqlServerPublisher.<ExecuteAsync>d__3.MoveNext() in C:\projects\cap\src\DotNetCore.CAP.SqlServer\ICapPublisher.SqlServer.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Abstractions.CapPublisherBase.<PublishAsyncInternal>d__13.MoveNext() in C:\projects\cap\src\DotNetCore.CAP\Abstractions\CapPublisherBase.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Abstractions.CapPublisherBase.Publish[T](String name, T contentObj, String callbackName) in C:\projects\cap\src\DotNetCore.CAP\Abstractions\CapPublisherBase.cs:line 51
   at CAP.Web.Controllers.HomeController.Publish(String message) in F:\work\demo\A\CAP.Demo\CAP.Web\Controllers\HomeController.cs:line 49
ClientConnectionId:25d10f2e-3f51-4ac2-a42a-9b44bc69ff56
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
please see release notes of v2.4.0 
https://github.com/dotnetcore/CAP/releases
