### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ww198643** [dotnetcore/CAP#302]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.ConsumerHandler.Dispose() in C:\projects\cap\src\DotNetCore.CAP\IConsumerHandler.Default.cs:line 85
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Shop.BasketService.Program.Main(String[] args) in F:\GitHub\MicroServicesShop\src\Shop.BasketService\Program.cs:line 65
   at Shop.BasketService.Program.<Main>(String[] args)

**Comment by ww198643** [comment]
![image](https://user-images.githubusercontent.com/17895675/54676121-ea252500-4b3a-11e9-93a4-760277b6c1a6.png)
自定义交换机的名字就会报这个错

**Comment by yang-xiaodong** [comment]
Your issue is not due to the error of setting the `ExchangeName`, but because of an exception at you app startup. So DI raises a bug when calling 'DotNetCore.CAP.ConsumerHandler.Dispose()` when releasing the object and we has been fixed this.

So You need to find errors in your startup process.
