### ISSUE TITLE
The use of message queues for sending in timed tasks causes deadlock problems

### ISSUE THREAD

**Issue by zhenlei520** [dotnetcore/CAP#313]
## The use of message queues for sending in timed tasks causes deadlock problems

dependencies version：
DotNetCore.CAP：2.2.5
DotNetCore.CAP.MySql：2.2.5
DotNetCore.CAP.RabbitMQ：2.2.5

HangFire：1.6.20
Hangfire.MySql.Core：2.1.7

HangFire timing task is used in the project to process long overdue orders, change order status, and send message queue to release inventory, but it will prompt after long running。

            MySql.Data.MySqlClient.MySqlException (0x80004005): Deadlock found when trying to get lock; try restarting transaction ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Deadlock found when trying to get lock; try restarting transaction
    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
    at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
    at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
    at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
    at Hangfire.MySql.Core.JobQueue.MySqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
    warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
        Processor 'DotNetCore.CAP.Processor.NeedRetryMessageProcessor' failed. Retrying...
    MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired. ---> System.ObjectDisposedException: Cannot access a disposed object.
    Object name: 'System.Net.Sockets.Socket'.
    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
    at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
    at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
    at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 749
    at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
    at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 272
    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
    at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 405
    at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 175
    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
    at DotNetCore.CAP.MySql.MySqlStorageConnection.GetPublishedMessagesOfNeedRetry()
    at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessPublishedAsync(IStorageConnection connection, ProcessingContext context)
    at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessAsync(ProcessingContext context)
    at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
    warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
        Processor 'DotNetCore.CAP.MySql.MySqlCollectProcessor' failed. Retrying...

        MySql.Data.MySqlClient.MySqlException (0x80004005): Deadlock found when trying to get lock; try restarting transaction ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Deadlock found when trying to get lock; try restarting transaction
    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
    at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
    at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
    at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
    at Hangfire.MySql.Core.JobQueue.MySqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
    fail: Hangfire.MySql.Core.JobQueue.MySqlJobQueue[0]
        Deadlock found when trying to get lock; try restarting transaction

A deadlock was sent in the error message, but no deadlock was found in the timed task after inspection. It is suspected that Cap is misconfigured. The following is the configuration information，The complete code is as follows

     public class Startup
    {
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.AddMvc();
            services.AddHttpClient();

            services.AddDbContext<OrderDbContext>();

           var _rabbitMqOptions = new RabbitMQOptions()
            {
                HostName = Configuration.GetSection("RabbitMqConfig")["HostName"],
                Port = Configuration.GetSection("RabbitMqConfig")["Port"].ConvertToInt(0),
                UserName = Configuration.GetSection("RabbitMqConfig")["UserName"],
                Password = Configuration.GetSection("RabbitMqConfig")["Password"],
                VirtualHost = Configuration.GetSection("RabbitMqConfig")["VirtualHost"]
            };

            services.AddCap(x =>
            {
                x.UseEntityFramework<OrderDbContext>();
                x.UseRabbitMQ(options =>
                {
                    options.HostName = _rabbitMqOptions.HostName;
                    options.Port = _rabbitMqOptions.Port;
                    options.UserName = _rabbitMqOptions.UserName;
                    options.Password = _rabbitMqOptions.Password;
                    options.VirtualHost = _rabbitMqOptions.VirtualHost;
                });

                x.FailedThresholdCallback =
                    (type, name, content) =>
                    {
                        Utils.GetLogService().Error("CAP异常",
                            "MessageType：" + type + "\n" + "Name：" + name + "\n" + "Content：" + content);
                    };
            });

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            //hangfire配置
            services.AddHangfire(t => t.UseStorage(new MySqlStorage(
                Configuration.GetSection("AppConfig")["DbConn"] + "Allow User Variables=true;",
                new MySqlStorageOptions
                {
                    TransactionIsolationLevel = IsolationLevel.ReadCommitted,
                    QueuePollInterval = TimeSpan.FromSeconds(15),
                    JobExpirationCheckInterval = TimeSpan.FromHours(1),
                    CountersAggregateInterval = TimeSpan.FromMinutes(5),
                    PrepareSchemaIfNecessary = true,
                    DashboardJobListLimit = 50000,
                    TransactionTimeout = TimeSpan.FromMinutes(10),
                })));

           ………………………………………………Ioc injection elision………………………………………………

            return _serviceProvider;
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseCap();
            app.UseHangfireServer();
            
            //Enable timed tasks
            BaseServiceProvider.Configuration();
        }
    }

     public class BaseServiceProvider
         {
             public static void Configuration()
             {
                 new JobBase().StartJob();
             }
     
             protected static IServiceProvider BuildProvider()
             {
                 IServiceCollection services = new ServiceCollection();
     
                 services.AddScoped(t => Utils.GetServiceProvider().GetService<AppConfig>());
                 services.AddScoped(typeof(IUnitOfWork), typeof(OrderDbContext));
                 services.AddScoped(typeof(IRepository<,>), typeof(RepositoryBase<,>));
                 services.AddScoped(typeof(IQuery<,>), typeof(QueryBase<,>));
                 services.AddHttpClient();
                 var servicesProvider = services.BuildServiceProvider();
                 return servicesProvider;
             }
         }

        /// <summary>
        /// 
        /// </summary>
        public class JobBase : BaseServiceProvider
        {
            /// <summary>
            /// 
            /// </summary>
            public void StartJob()
            {
                if (DYCloud.Infrastructure.Core.Utils.GetAppConfig().RunTask)
                {
                    CheckBuyerOrdersConfigGoods.Run();
                }
            }
        }

        public class CheckBuyerOrdersConfigGoods : JobBase
    {
        public static void Run()
        {
            using (IServiceScope serviceScope =
                BuildProvider().CreateScope())
            {
                var provider = serviceScope.ServiceProvider;
                var capPublisher = provider.GetService<ICapPublisher>();
                capPublisher.Publish("routeKey","content");
            }
        }
    }

**Comment by yang-xiaodong** [comment]
Have you solved the problem?Looks like didn't cause it by CAP

**Comment by yang-xiaodong** [comment]
no response ,close

**Comment by zhenlei520** [comment]
No solution has been found for the time being
