### ISSUE TITLE
asp.net core 2.0 not compatibility

### ISSUE THREAD

**Issue by simhgd** [dotnetcore/CAP#32]
when in asp.net core 2.0
in ConfigureServices AddCap -- UseEntityFramework, UseRabbitMQ
in Configure UseCap

runtime throw

Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.

StackTrace:
   at DotNetCore.CAP.SqlServerCapOptionsExtension.TempBuildService(IServiceCollection services)
   at DotNetCore.CAP.SqlServerCapOptionsExtension.AddServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCap(IServiceCollection services, Action`1 setupAction)
   at namespace.Startup.ConfigureServices(IServiceCollection services)

**Comment by yuleyule66** [comment]
An official version of 2.0 has yet to be released, you can use the preview version now.

**Comment by simhgd** [comment]
Thank you for your prompt reply. wish 2.0 final version faster.

**Comment by yuleyule66** [comment]
@simhgd 
version 2.0 preview published, it used .net standard 2.0 also support .net core 2.0 and asp.net core 2.0.
