### ISSUE TITLE
UseDashboard还是看不见dashboard

### ISSUE THREAD

**Issue by mswinner** [dotnetcore/CAP#328]
版本2.31 win10 
.net core2.2 

http://127.0.0.1:5000/cap  无法访问

     services.AddCap(x =>
            {
                x.UseDashboard();
                x.UseEntityFramework<Infrastructure.EntityFrameworkDataAccess.Context>();
                x.UseRabbitMQ("127.0.0.1");
            });

Content root path: D:\Project\Company\FlameTyreMES-git\Host
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
dbug: DotNetCore.CAP.SqlServer.SqlServerCollectProcessor[0]
      Collecting expired data from table [Cap].[Published].
info: DotNetCore.CAP.DefaultBootstrapper[0]
      ### CAP started!
dbug: DotNetCore.CAP.SqlServer.SqlServerCollectProcessor[0]
      Collecting expired data from table [Cap].[Received].
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 56.4742ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/cap
f**ail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLM8BRD5JIFT", Request id "0HLM8BRD5JIFT:00000002": An unhandled exception was thrown by the application.**
System.Data.SqlClient.SqlException (0x80131904): 'FORMAT' 不是可以识别的 内置函数名称。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1053
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at DotNetCore.CAP.SqlServer.SqlServerMonitoringApi.GetTimelineStats(IDbConnection connection, String tableName, String statusName, IDictionary`2 keyMaps) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\IMonitoringApi.SqlServer.cs:line 190
   at DotNetCore.CAP.SqlServer.SqlServerMonitoringApi.GetHourlyTimelineStats(IDbConnection connection, String tableName, String statusName) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\IMonitoringApi.SqlServer.cs:line 160
   at DotNetCore.CAP.SqlServer.SqlServerStorage.UseConnection[T](Func`2 func) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\IStorage.SqlServer.cs:line 118
   at DotNetCore.CAP.Dashboard.Pages.HomePage.Execute() in C:\projects\cap\src\DotNetCore.CAP\HomePage.cshtml:line 11
   at DotNetCore.CAP.Dashboard.RazorPage.TransformText(String body) in C:\projects\cap\src\DotNetCore.CAP\Dashboard\RazorPage.cs:line 167
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) in C:\projects\cap\src\DotNetCore.CAP\Dashboard\RazorPageDispatcher.cs:line 24
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context) in C:\projects\cap\src\DotNetCore.CAP\Dashboard\CAP.DashboardMiddleware.cs:line 65
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
ClientConnectionId:db6c4e8e-e00e-4d63-b72b-845a01624f61
Error Number:195,State:10,Class:15
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 192.905ms 500

**Comment by mswinner** [comment]
sql 版本问题 2008r2 不行
我换成2017 ok

**Comment by mswinner** [comment]
是否可以考虑支持一下 sql2008r2 数据库

The FORMAT function is only available in SQL Server 2012+.

Formatting dates in 2008 and earlier is a bit cumbersome. You can do

RIGHT(CAST(YEAR([ShippedDate]) AS NVARCHAR(4)), 2) 
    + RIGHT('0' + CAST(MONTH([ShippedDate]) AS NVARCHAR(2)), 2)

**Comment by yang-xiaodong** [comment]
cap=>{cap.AddSqlServer(x=>x..UseSqlServer2008())}

**Comment by mswinner** [comment]
x.UseEntityFramework<Infrastructure.EntityFrameworkDataAccess.Context>(e=>e.UseSqlServer2008());
