### ISSUE TITLE
Only READPAST locks can be specified at the READ COMMITTED or REPEATABLE READ isolation level.

### ISSUE THREAD

**Issue by CacoCode** [dotnetcore/CAP#352]
2019-06-20 08:03:12.5425servicename=ShipMainService--Processor 'DotNetCore.CAP.Processor.NeedRetryMessageProcessor' failed. Retrying...System.Data.SqlClient.SqlException (0x80131904): Only READPAST locks can be specified at the READ COMMITTED or REPEATABLE READ isolation level.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass190_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 437
   at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.GetPublishedMessagesOfNeedRetry() in C:\projects\cap\src\DotNetCore.CAP.SqlServer\IStorageConnection.SqlServer.cs:line 49
   at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessPublishedAsync(IStorageConnection connection, ProcessingContext context) in C:\projects\cap\src\DotNetCore.CAP\Processor\IProcessor.NeedRetry.cs:line 45
   at DotNetCore.CAP.Processor.NeedRetryMessageProcessor.ProcessAsync(ProcessingContext context) in C:\projects\cap\src\DotNetCore.CAP\Processor\IProcessor.NeedRetry.cs:line 40
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context) in C:\projects\cap\src\DotNetCore.CAP\Processor\IProcessor.InfiniteRetry.cs:line 29
ClientConnectionId:7d2faa60-9da9-4008-ae58-d39d7345c59a
Error Number:650,State:1,Class:16

**Comment by CacoCode** [comment]
Action<CapOptions> capOptions = option =>
            {
                option.UseEntityFramework<AdminDbContext>();
                //option.UseSqlServer(_appConfiguration.GetConnectionString("Default"));
                option.UseRabbitMQ("localhost");
                option.UseDashboard();
                if (Convert.ToBoolean(_appConfiguration["Cap:UseConsul"]))
                {
                    option.UseDiscovery(discovery =>
                    {
                        discovery.DiscoveryServerHostName = _appConfiguration["Cap:DiscoveryServerHostName"];
                        discovery.DiscoveryServerPort = Convert.ToInt32(_appConfiguration["Cap:DiscoveryServerPort"]);
                        discovery.CurrentNodeHostName = _appConfiguration["Cap:CurrentNodeHostName"];
                        discovery.CurrentNodePort = Convert.ToInt32(_appConfiguration["Cap:CurrentNodePort"]);
                        discovery.NodeId = Convert.ToInt32(_appConfiguration["Cap:NodeId"]);
                        discovery.NodeName = _appConfiguration["Cap:NodeName"];
                        discovery.MatchPath = _appConfiguration["Cap:MatchPath"];
                    });
                }

            };

**Comment by yang-xiaodong** [comment]
To resolve this problem, configure to use the REPEATABLE READ isolation level in Microsoft SQL Server instead of the SERIALIZABLE isolation level.

**Comment by CacoCode** [comment]
> To resolve this problem, configure to use the READ COMMITTED or REPEATABLE READ isolation level in Microsoft SQL Server instead of the SERIALIZABLE isolation level.
 
sql server has set ‘set transaction isolation level read committed;’, but this problem still occurs

**Comment by tohkinzhu** [comment]
Have you solved this issue?
We have the same one, we are using Aliyun SQL SERVER2016 WEB
@CacoCode
