### ISSUE TITLE
Processor 'DotNetCore.CAP.MySql.MySqlCollectProcessor' failed. Retrying

### ISSUE THREAD

**Issue by k-yaobo** [dotnetcore/CAP#359]
并发高的时候。CAP不断出这个警告。求解答

$[2019-07-03 16:47:13.7894]#WARN#####Processor 'DotNetCore.CAP.MySql.MySqlCollectProcessor' failed. Retrying...# at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 81
at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 317
at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 302
at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 276
at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
at DotNetCore.CAP.MySql.MySqlCollectProcessor.ProcessAsync(ProcessingContext context)
at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)#$end$

**Comment by yang-xiaodong** [comment]
How can I repetition this warning?

**Comment by k-yaobo** [comment]
起10个线程。每个线程一分钟发5000个消息。 持续1小时，就会不断出问题

**Comment by k-yaobo** [comment]
> How can I reproduce this warning?

好像 消息一多。消费不过来。就会出这个警告，或者异常

**Comment by yang-xiaodong** [comment]
Is there any exception about this warning,  it looks the database raise an error?

**Comment by k-yaobo** [comment]
嗯。是的。DB瓶颈导致CAP不断异常。 我换了一台比较好的服务器。同样在大概10分钟内写入12万条消息。这次CAP表只有一条记录失败。

 "ExceptionMessage": {
    "Source": "DotNetCore.CAP",
    "Message": "Fatal error encountered during command execution.",
    "InnerMessage": "Fatal error encountered during command execution."
  }

![QQ截图20190704110538](https://user-images.githubusercontent.com/21329253/60637292-78a08680-9e4c-11e9-96ba-bc5ffa156184.png)

**Comment by k-yaobo** [comment]
还有一个问题，CAP 项目里的RabbitMQ。不能设置BasicQos 服务质量保证的功能吗？ 当然消息量大的时候。一下子涌进来。published，received，两个表读写太过于频繁也会直接影响DB

**Comment by yang-xiaodong** [comment]
We have improved RabbitMQOptions to provide extensions option to configure the client original configuration in v2.5.1
usage see #350
