### ISSUE TITLE
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Error parsing boolean value.

### ISSUE THREAD

**Issue by marrrschine** [dotnetcore/CAP#385]
Hi,
first of all, nice work! Thanks for such a cool project. 

I'm trying to get fimiliar with CAP but unfortunatelly get this exception:

```
[16:36:12 ERR] An exception occurred while executing the subscription method. Topic:inbound.topic.test, Id:1162040302759854080
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Error parsing boolean value. Path '', line 1, position 1. ---> Newtonsoft.Json.JsonReaderException: Error parsing boolean value. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseTrue()
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at DotNetCore.CAP.Infrastructure.Helper.FromJson[T](String value) in C:\projects\cap\src\DotNetCore.CAP\Infrastructure\Helper.cs:line 33
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.InvokeAsync(ConsumerContext context) in C:\projects\cap\src\DotNetCore.CAP\Internal\IConsumerInvoker.Default.cs:line 46
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 181
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 194
   at DotNetCore.CAP.DefaultSubscriberExecutor.ExecuteWithoutRetryAsync(CapReceivedMessage message) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 88
The program 'dotnet' has exited with code 0 (0x0).
```

**I'm running CAP 2.5.1 in ASP.NET Core 2.2.6.**

This is my Startup.cs (relevant section):

```
        public static IServiceCollection AddEventBus(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddTransient<MessageHandler>();

            services.AddCap(cap =>
            {
                cap.UseInMemoryStorage();
                cap.UseRabbitMQ(conf =>
                {
                    conf.ExchangeName = "cap.default.router"; // only for testing purposes
                    conf.HostName = configuration.GetValue<string>("EVENTBUS_HOSTNAME");
                    conf.Port = Convert.ToInt32(configuration.GetValue<int>("EVENTBUS_PORT"));
                    conf.UserName = configuration.GetValue<string>("EVENTBUS_USER");
                    conf.Password = configuration.GetValue<string>("EVENTBUS_PASS");
                });
                cap.UseDashboard();
            });

            return services;
        }
```

The `MessageHandler` defines:

```
[CapSubscribe("inbound.topic.test")]
public void CheckReceived(string message)
{
    _logger.LogInformation(message);
}
```

Inside RabbitMQ Admin I can see:
- 1 Exchange (Name: cap.default.router, Type: topic) with 1 Binding (This exchange => to: Queue cap.queue.deviceservice.v1, Routing key: inbound.topic.test)
- 1 Queue (Name: cap.queue.deviceservice.v1, Consumers: 1 Channel [amq.ctag-***]) with 1 Default exchange binding (from: cap.default.router, Routing key: inbound.topic.test) => to: This queue

I was trying to publish a message via RabbitMQ Admin interface, from inside the Exchanges tab:

![image](https://user-images.githubusercontent.com/1773639/63112001-59d6f900-bf8f-11e9-838d-068ac6a253bc.png)

What am I missing? Thanks in advance.

**Comment by yang-xiaodong** [comment]
Hello, 

CAP has wrapper the original user's date message to a new payloads. If you send payloads directly via RabbitMQ Admin interface, An exception will be thrown when deserializing..

Our ongoing version has made some adjustments of the data structure, it will directly use the original user data to message queue's payloads, but has not yet released.

In the currently released version, you need to send a message like this:

```
 _capBus.Publish("inbound.topic.test","the user messages");
```

**Comment by marrrschine** [comment]
thank you for the fast response. 
Does that mean that (right now) I can only subscribe to messages from inside the "CAP world"?

**Comment by yang-xiaodong** [comment]
If you want to consume data from other systems, you need to adjust the data that does not follow the CAP message format.

See the docs:
http://cap.dotnetcore.xyz/user-guide/en/cap/serialization/#message-adapter

**Comment by marrrschine** [comment]
Ok, thank you. One last question: Does the message adapter know Headers and Parameters (see my sceenshop above) or does your raw CapMessage contain these?
