### ISSUE TITLE
ArgumentOutOfRangeException或ObjectDisposedException异常

### ISSUE THREAD

**Issue by kulend** [dotnetcore/CAP#45]
RabbitMQ&Mysql环境

当我publish一条消息后，如果没有在Controller添加任何CapSubscribe属性的action，则报以下错误
`
System.ArgumentOutOfRangeException:` Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DotNetCore.CAP.SubscibeQueueExecutor.<ExecuteSubscribeAsync>d__7.MoveNext()
`
然后写了CapSubscribe属性的action，则会报以下出错信息
`
System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.<InvokeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.SubscibeQueueExecutor.<ExecuteSubscribeAsync>d__7.MoveNext()
`

**Comment by yuleyule66** [comment]
你使用最新的 2.0.1-preview-21392243 版本，看是否还有此问题？

**Comment by kulend** [comment]
还是有问题。
![_20170908103345](https://user-images.githubusercontent.com/29294609/30193690-38ba90c8-9481-11e7-9314-a6ef734e130b.png)
这里需要实例化controller，但貌似已经不在一个请求的生命周期内了。

**Comment by yuleyule66** [comment]
Controller 和 CAP Subscribe 的调用是不在一个生命周期的

**Comment by yuleyule66** [comment]
你贴一下你的代码，我怎么样才能复现你的问题？

**Comment by kulend** [comment]
发现问题所在了，controller的构造函数是这样的
`
        private IUserActionLogService service;
        public LogController(IUserActionLogService service)
        {
            this.service = service;
        }
`
注册service是InstancePerLifetimeScope
`
            builder.RegisterAssemblyTypes(typeof(IUserService).GetTypeInfo().Assembly)
                .Where(t => t.Name.EndsWith("Service", StringComparison.CurrentCultureIgnoreCase))
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope();
`
这样IUserActionLogService就没法实例化，然后就报上面的错了。
不知道大神有没有好的解决办法？

**Comment by kulend** [comment]
使用ICapSubscribe Service也有同样的问题，这个问题希望能解决下，总不可能Subscribe用到的都必须注册成Singleton或是Transient吧？

**Comment by yuleyule66** [comment]
你用的Autofac？

**Comment by kulend** [comment]
@yuleyule66 

是的，用的是Autofac

**Comment by yuleyule66** [comment]
没有测试过Autofac，CAP内容拿Services都是微软的DI的，建议切换为微软DI

**Comment by kulend** [comment]
亲测真和autofac有关系，那这个是autofac的锅?

**Comment by kulend** [comment]
@yuleyule66 
我调试了cap的代码，貌似是有点问题。
在\src\DotNetCore.CAP\IQueueExecutor.Subscibe.cs第107行：
await _consumerInvokerFactory.CreateInvoker(consumerContext).InvokeAsync();
CreateInvoker里面，using (var scope = _serviceProvider.CreateScope())，但返回了才去InvokeAsync，那这个scope已dispose掉了吧。Invoke会去实例化controller，然后就报错了。
这个地方我把InvokeAsync移到using里面测试就正常了。
        public async Task CreateInvokerAndInvokeAsync(ConsumerContext consumerContext)
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                var context = new ConsumerInvokerContext(consumerContext)
                {
                    Result = new DefaultConsumerInvoker(_logger, scope.ServiceProvider, _modelBinderFactory, consumerContext)
                };
                await context.Result.InvokeAsync();
            }
        }

**Comment by yuleyule66** [comment]
这里看起来好像有问题，但是我这边复现不到呢？ 你是怎么测试出来的呢？

**Comment by yuleyule66** [comment]
@kulend  升级  `2.0.1-preview-21993007`  再看一下有没有问题呢
