### ISSUE TITLE
Azure service bus not working in CAP version 3.0

### ISSUE THREAD

**Issue by eheinz57** [dotnetcore/CAP#483]
We've been developing using your library for months now and we haven't seen this error as of yet.
After upgrading to v3, we are now receiving this error below for all subscribers:

[41m[30mfail[39m[22m[49m: DotNetCore.CAP.Internal.ConsumerRegister[0]
      AzureServiceBus subscriber received an error. --> - Endpoint: XXXXX.servicebus.windows.net
      - Entity Path: cap/Subscriptions/Client.v1
      - Executing Action: UserCallback
      - Exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClient.<>c.<OnConsumerReceived>b__20_1(KeyValuePair`2 y)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClient.OnConsumerReceived(Message message, CancellationToken token)
         at Microsoft.Azure.ServiceBus.MessageReceivePump.MessageDispatchTask(Message message)

We are using Sql, EF, and Azure service bus.  SQL shows the published message as successful, but the received table never shows an entry.

The Client.v1 subscription ends up having a deadletter mesage in the queue.

Any ideas on what I can do to troubleshoot further?

**Comment by yang-xiaodong** [comment]
Since my azure free subscription has expired, so I cannot test the ASB. 

The exception that is thrown is due to the null reference exception that is thrown during the type 
conversion of the header. 

Code is here:
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs#L162

You can submit a PR to fix this error.

**Comment by eheinz57** [comment]
Ok thank you.  I'll take a look and get back to you via the PR flow.

**Comment by yang-xiaodong** [comment]
Fixed in version 3.0.1

**Comment by eheinz57** [comment]
Thank you for making the correction.  I tested in azure with 3.0.1 and now I get this exception:

DotNetCore.CAP.Internal.ConsumerRegister[0]
      An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at DotNetCore.CAP.Internal.MethodMatcherCache.TryGetTopicExecutor(String topicName, String groupName, ConsumerExecutorDescriptor& matchTopic)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass20_0.<<RegisterMessageProcessor>b__0>d.MoveNext()

**Comment by thisispaulsmith** [comment]
I'm also getting the message above?

**Comment by yang-xiaodong** [comment]
@thisispaulsmith would you like to submit a PR to fix it?

**Comment by thisispaulsmith** [comment]
> @thisispaulsmith would you like to submit a PR to fix it?

I've created a separate issue for it. Will try and look at it next week.
