### ISSUE TITLE
Key deserialization error

### ISSUE THREAD

**Issue by lsy520** [dotnetcore/CAP#513]
Confluent.Kafka.ConsumeException: Local: Key deserialization error ---> System.ArgumentException: Deserializer<Null> may only be used to deserialize data that is null.
   at Confluent.Kafka.Deserializers.NullDeserializer.Deserialize(ReadOnlySpan`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
   at DotNetCore.CAP.ConsumerRegister.<>c__DisplayClass15_0.<Start>b__0()

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
