### ISSUE TITLE
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable

### ISSUE THREAD

**Issue by CheckyChen** [dotnetcore/CAP#561]
你好，
在服务启动的时候包了这个错误，发布服务启动后，提示 ### CAP started!，但是订阅那个服务启动的时候报了下面这个错误，在触发一个发布事件时，cap.published 表中有数据，cap.received表没数据，是哪里少了配置？

fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
      Broker Unreachable
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'microservice_test_queue' in vhost 'microservice_test': received 'topic' but current is 'direct'", classId=40, methodId=10, cause=
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ExchangeDeclare(String exchange, String type, Boolean passive, Boolean durable, Boolean autoDelete, Boolean internal, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.ExchangeDeclare(String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.AutorecoveringModel.ExchangeDeclare(String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments)
   at RabbitMQ.Client.IModelExensions.ExchangeDeclare(IModel model, String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments)
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Connect()
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_0.<Start>b__0()

服务1Startup.cs，发布：
 services.AddCap(option =>
            {
                option.UseRabbitMQ(opt =>
                {
                    opt.HostName = "localhost";
                    opt.UserName = "guest";
                    opt.Password = "guest";
                    opt.VirtualHost = "microservice_test";
                    opt.ExchangeName = "microservice_test_queue";
                });

                option.UseMySql("server=127.0.0.1;database=microservice_rbmq;userid=root;password=123456;");
            });

服务2Startup.cs，订阅：
 services.AddCap(option =>
            {
                

                option.UseRabbitMQ(opt =>
                {
                    opt.HostName = "localhost";
                    opt.UserName = "guest";
                    opt.Password = "guest";
                    opt.VirtualHost = "microservice_test";
                    opt.ExchangeName = "microservice_test_queue";
                });

                option.UseMySql("server=127.0.0.1;database=microservice_rbmq;userid=root;password=123456;");
            });

**Comment by yang-xiaodong** [comment]
You typically get that error message when you re-declare an existing queue with different parameters. Check in the management console to see if the queue already exists. If it does, try deleting it and then re-running your code.
