### ISSUE TITLE
ado.net with dapper get an exception

### ISSUE THREAD

**Issue by wswind** [dotnetcore/CAP#570]
my demo repo:
https://github.com/wswind/Learn-CAP/tree/master/Api1

I use dapper with cap.

```
  services.AddCap(x =>
            {
                // If you are using ADO.NET, choose to add configuration you needed：
                x.UseSqlServer("Server=.;Database=BFF;Trusted_Connection=True;MultipleActiveResultSets=true");
                x.UseRabbitMQ(o => {
                    o.HostName = "192.168.56.10";
                    o.UserName = "rabbit";
                    o.Password = "rabbit";
                });
            });


        [Route("~/adonet/transaction")]
        public IActionResult AdonetWithTransaction()
        {
            using (var connection = _sqlFactory.CreateConnection())
            {
                using (var transaction = connection.BeginTransaction(_capBus, autoCommit: true))
                {
                    //your business logic code
                    TestTable testTable = new TestTable()
                    {
                        A = "f",
                        B = "g"
                    };
                    connection.Insert<TestTable>(testTable, transaction);
                    _capBus.Publish("testtable.insert", testTable); ## here is the exception
                }
            }
            return Ok();
        }
```

But an exception occurs when try to publish the message to rabbitmq.

![image](https://user-images.githubusercontent.com/18399096/82525644-73335400-9b64-11ea-9e93-28d428a6ba0c.png)

call stack:
```
   at DotNetCore.CAP.SqlServerCapTransaction.AddToSent(MediumMessage msg)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, IDictionary`2 headers)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, String callbackName)
   at Api1.Controllers.PublishController.AdonetWithTransaction() in D:\repos\open-mine\Learn-CAP\Api1\Controllers\PublishController.cs:line 36
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
```
I use System.Data.SqlClient to create SqlConnection,I didn't use Microsoft.Data.SqlClient.
What shall I do to fix this error?

**Comment by yang-xiaodong** [comment]
The `Microsoft.Data.SqlClient` is the feature of SQL Server client,  we recommend switch it

**Comment by wswind** [comment]
thanks for your help.
