### ISSUE TITLE
Kafka Produce Message Error

### ISSUE THREAD

**Issue by FeynmanLoo** [dotnetcore/CAP#572]
i got error message when publish event use _cap.PublishAsync("topic", @event) in Console base on DotNetCore 3.1.101 .
```C#
[09:40:25 ERR] An exception occurred when sending a message to the MQ. Id:1263645855633043596
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Confluent.Kafka.DeliveryResult`2<!0,!1>> Confluent.Kafka.IProducer`2.ProduceAsync(System.String, Confluent.Kafka.Message`2<!0,!1>)'.
   at DotNetCore.CAP.Kafka.KafkaTransport.SendAsync(TransportMessage message)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.Kafka.KafkaTransport.SendAsync(TransportMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendWithoutRetryAsync(MediumMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendAsync(MediumMessage message)
   at DotNetCore.CAP.Processor.Dispatcher.Sending()

```

But when I  change to use Rabbitmq or reference the source code of DotNet.Cap.Kafka and upgrade Confluent.Kafka 1.3.0 to 1.4.3 , they both works !!!

**Comment by yang-xiaodong** [comment]
we have upgrade kafka client to 1.4.3
