### ISSUE TITLE
Type conversion exception

### ISSUE THREAD

**Issue by xxdnet** [dotnetcore/CAP#582]
When using hangfire in the project, cap has an exception. The exception information is as follows:

System.InvalidCastException
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.

System.InvalidCastException: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.
   at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteTransactionCommitAfter(DiagnosticListener this, Guid operationId, IsolationLevel isolationLevel, SqlConnection connection, String operation)
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP/issues/570#issuecomment-631963668
