### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.Collections.Async.IAsyncEnumerable`1<!!0> 

### ISSUE THREAD

**Issue by captmomo** [dotnetcore/CAP#607]
```
2020-07-11 00:00:33.852 +08:00 [WRN] Get messages of type 'CapPublishedMessage' failed. Retrying...
System.MissingMethodException: Method not found: 'System.Collections.Async.IAsyncEnumerable`1<!!0> System.Collections.Generic.IEnumerableExtensions.ToAsyncEnumerable(System.Collections.Generic.IEnumerable`1<!!0>, Boolean)'.
```

This error keeps appearing in my log, I'm not quite sure where it it is coming from as I do no use IAsyncEnumerable.

```
2020-07-11 00:00:26.237 +08:00 [INF] Total events in queue: 0
		
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetPublishedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetPublishedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
2020-07-11 00:00:33.853 +08:00 [WRN] Get messages of type 'CapReceivedMessage' failed. Retrying...
System.MissingMethodException: Method not found: 'System.Collections.Async.IAsyncEnumerable`1<!!0> System.Collections.Generic.IEnumerableExtensions.ToAsyncEnumerable(System.Collections.Generic.IEnumerable`1<!!0>, Boolean)'.
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetReceivedMessagesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetReceivedMessagesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Func`1 getMessagesAsync)
2020-07-11 00:00:36.252 +08:00 [INF] Total events in queue: 0
```

**Comment by yang-xiaodong** [comment]
Please provide you environment and CAP version, make sure you are using at .NET Core, CAP also do no use IAsyncEnumerable.

**Comment by yang-xiaodong** [comment]
No response, close
