### ISSUE TITLE
Error when starting dashboard page

### ISSUE THREAD

**Issue by hilkenan** [dotnetcore/CAP#639]
When i try to load the /cap url from browser it I on the CAP Version 3.1.0 the following errror:
 An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to resolve service for type 'DotNetCore.CAP.Dashboard.NodeDiscovery.INodeDiscoveryProvider' while attempting to Invoke middleware 'DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware'.
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServiceProvider sp, Type type, Type middleware)
   at lambda_method(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

I Start CAP as following:
            services.AddCap(x =>
            {
                x.UseEntityFramework<AnyDbContext>();
                x.UseRabbitMQ(conf =>
                {
                    conf.HostName = "localhost";
                    conf.UserName = "xxx";
                    conf.Password = "xxx";
                    conf.Port = 5672;
                });
                x.UseDashboard();
            });

Any Idea?

**Comment by yang-xiaodong** [comment]
Hello, I can’t reproduce your issue, please make sure that your version is correctly, and if you have configured x=>x.UseDiscovery() if you want to use node discovery

**Comment by yang-xiaodong** [comment]
No response, close

**Comment by hilkenan** [comment]
Sorry for my late response here: 
- I use the latest Version 3.1.0
- Here My Discovery Config:
                    d.DiscoveryServerHostName = "localhost";
                    d.DiscoveryServerPort = 8500;
                    d.CurrentNodeHostName = "localhost";
                    d.CurrentNodePort = 5672;
                    d.NodeId = "1";
                    d.NodeName = "CAP No.1 Node";

If I use this Config i get another error:
 Get consul nodes raised an exception. Exception:Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.,Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
       [Bfs.Sis.Configurator.Api,2f90ed482ad6fe18,3a00e9ad6d189bd6,,false] Connection id "0HM2DFN0GVU4C", Request id "0HM2DFN0GVU4C:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Dashboard.RazorPage.SetServersCount(StatisticsDto dto)
   at DotNetCore.CAP.Dashboard.RazorPage.<Assign>b__55_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at DotNetCore.CAP.Dashboard.RazorPage.get_Statistics()
   at DotNetCore.CAP.Dashboard.Pages.HomePage.Execute()
   at DotNetCore.CAP.Dashboard.RazorPage.TransformText(String body)
   at DotNetCore.CAP.Dashboard.RazorPage.ToString()
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.Invoke(HttpContext context, DiscoveryOptions discoveryOptions, INodeDiscoveryProvider discoveryProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Any Idee? I not sure aboud the Discovery Config. At least at the ports: What for Ports i have to use?

**Comment by yang-xiaodong** [comment]
please refer: https://github.com/dotnetcore/CAP/issues/490#issuecomment-575620873
