### ISSUE TITLE
 Method not found: 'Void RabbitMQ.Client.IModelExensions.BasicPublish

### ISSUE THREAD

**Issue by wjkhappy14** [dotnetcore/CAP#650]
连接Rabbit都OK，然后Publish 的时候，早就出了这个异常呢？
使用的是 RabbitMQ.Client  Version=6.2.1

System.MissingMethodException: Method not found: 'Void RabbitMQ.Client.IModelExensions.BasicPublish(RabbitMQ.Client.IModel, System.String, System.String, RabbitMQ.Client.IBasicProperties, Byte[])'.
   at DotNetCore.CAP.RabbitMQ.RabbitMQTransport.SendAsync(TransportMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendWithoutRetryAsync(MediumMessage message)
   at DotNetCore.CAP.Internal.MessageSender.SendAsync(MediumMessage message)
   at DotNetCore.CAP.Processor.Dispatcher.Sending()

**Comment by yang-xiaodong** [comment]
Please report your RabbitMQ version and CAP version

**Comment by yang-xiaodong** [comment]
No response, close
