### ISSUE TITLE
Consuming messages from exchange that has been published using other libraries.

### ISSUE THREAD

**Issue by captmomo** [dotnetcore/CAP#659]
Hi,

I am currently faced with an issue of consuming messages with CAP from an Exchange that has messages published using EasyNetQ.   

Are there any specific properties I need to append to the messages being published by EasyNetQ to make it work with CAP? 
Apologies if this is the wrong place to ask.

What is the alternative to `IMessagePacker ` since it has been removed?
```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern, RegexOptions options)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.MatchPoundUsingRegex(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.SelectBestCandidate(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.MethodMatcherCache.TryGetTopicExecutor(String topicName, String groupName, ConsumerExecutorDescriptor& matchTopic)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_0.<<RegisterMessageProcessor>b__0>d.MoveNext()
fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
      An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern, RegexOptions options)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.MatchPoundUsingRegex(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.SelectBestCandidate(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.MethodMatcherCache.TryGetTopicExecutor(String topicName, String groupName, ConsumerExecutorDescriptor& matchTopic)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_0.<<RegisterMessageProcessor>b__0>d.MoveNext()
```

**Comment by captmomo** [comment]
I have resolved this by adding the cap headers.

1. Create an adapter.
```
        public static Message<T> SetHeaders<T>(this Message<T> message, string fullName, string name)
        {
            var messageId = SnowflakeId.Default().NextId().ToString();
            var headers = message.Properties.Headers;
            message.Properties.Headers.Add(Headers.MessageId, messageId);
            headers.Add(Headers.MessageName, fullName);
            headers.Add(Headers.Type, name);
            headers.Add(Headers.SentTime, DateTimeOffset.Now.ToString());
            if (!headers.ContainsKey(Headers.CorrelationId))
            {
                headers.Add(Headers.CorrelationId, messageId);
                headers.Add(Headers.CorrelationSequence, 0.ToString());
            }
            return message;
        }
```
Usage:
```
            var mainType = newEvent.GetType();
            var mainMessage = new Message<TIntegrationEvent>(newEvent);
            mainMessage.SetHeaders(mainType.FullName, mainType.Name);
```

Hope this helps anyone experiencing the same issue.
