### ISSUE TITLE
kafka cap示例运行报错

### ISSUE THREAD

**Issue by gaoyangcaiji** [dotnetcore/CAP#678]
1.我把数据库改成了sqlserver

``` 
services.AddCap(x =>
            {
                x.UseSqlServer("")
                    .UseKafka(kafkaOpt =>
                {
                    kafkaOpt.Servers = "192.168.0.7:9092";
                });
                x.UseDashboard();
            });

            services.AddControllers();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        } 
```
调用堆栈：

```
DotNetCore.CAP.Internal.ConsumerRegister[0]
      An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
Microsoft.Data.SqlClient.SqlException (0x80131904): 参数化查询 '(@Id nvarchar(19),@Name nvarchar(4000),@Group nvarchar(35),@Cont' 需要参数 '@Name'，但未提供该参数。
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.StoreReceivedMessage(Object[] sqlParams)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.StoreReceivedExceptionMessage(String name, String group, String content)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_0.<<RegisterMessageProcessor>b__0>d.MoveNext()
ClientConnectionId:e10fce3a-2c9e-40eb-9fbe-c041937abfda
Error Number:8178,State:1,Class:16
```

**Comment by yang-xiaodong** [comment]
@xiangxiren Do you want to investigate for this issue?

**Comment by xiangxiren** [comment]
Unable to reproduce. Please provide version and configuration, and steps to reproduce.

**Comment by gaoyangcaiji** [comment]
thank you!Maybe I have solved this problem.my kafka version is 0.10.2.2.i find kafka  only after  version 0.11 can  supports headers.so i have to change annother way to implement may eventbus.
