### ISSUE TITLE
CAP Dashboard 报错 

### ISSUE THREAD

**Issue by maikebing** [dotnetcore/CAP#685]
DotNetCore.CAP.Dashboard 3.1.1 

项目:
https://github.com/IoTSharp/IoTSharp
容器版本:
mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim 

```
System.NullReferenceException: Object reference not set to an instance of an object.
at DotNetCore.CAP.Dashboard.RazorPage.SetServersCount(StatisticsDto dto)
at DotNetCore.CAP.Dashboard.RazorPage.<Assign>b__55_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at DotNetCore.CAP.Dashboard.RazorPage.get_Statistics()
at DotNetCore.CAP.Dashboard.Pages.HomePage.Execute()
at DotNetCore.CAP.Dashboard.RazorPage.TransformText(String body)
at DotNetCore.CAP.Dashboard.RazorPage.ToString()
at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.Invoke(HttpContext context, DiscoveryOptions discoveryOptions, INodeDiscoveryProvider discoveryProvider)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by xiangxiren** [comment]
Hi, please provide version, environment, configuration.so that we can reproduce.

**Comment by maikebing** [comment]
看起来是开启了 UseDiscovery 的原因
