### ISSUE TITLE
The given key 'cap.node' was not present in the dictionary 

### ISSUE THREAD

**Issue by AlphaYu** [dotnetcore/CAP#692]
### 访问/cap/nodes报500错误，步骤如下：

**1. 调用UseDiscovery扩展方法注册服务到consul，可以成功注册上，如下图。**
![consul](https://user-images.githubusercontent.com/23010680/96963575-6fed2b80-153b-11eb-9a07-2af8dff095b8.png)

**2. Dashboard也可以正常显示，如下图**
![dashboard](https://user-images.githubusercontent.com/23010680/96963793-e25e0b80-153b-11eb-8334-76287cf78098.png)

**3. 我点击servers，访问/cap/nodes，报500错误，详细信息如下**
```fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM3N3B9G5V69", Request id "0HM3N3B9G5V69:00000054": An unhandled exception was thrown by the application.
System.Collections.Generic.KeyNotFoundException: The given key 'cap.node' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DotNetCore.CAP.Dashboard.DashboardRoutes.<>c.<.cctor>b__2_8(DashboardContext x)
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at DotNetCore.CAP.Dashboard.GatewayProxy.GatewayProxyMiddleware.Invoke(HttpContext context, DiscoveryOptions discoveryOptions, INodeDiscoveryProvider discoveryProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by yang-xiaodong** [comment]
Hello , please show your configuration

**Comment by yang-xiaodong** [comment]
Hello, Have you checked these issues?  #629  #609  #540

**Comment by AlphaYu** [comment]
我用的是3.0.4版本。我看了#629 #609 #540，和我的问题一样。
但我升级到3.1.1,调试竟然报错了，错误内容如下：
```
An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> DotNetCore.CAP.Internal.ConsumerRegister.
```
我现在又回退到3.0.4了，编译无问题。

我的配置如下。
```
            _services.AddCap(x =>
            {
                //如果你使用的 EF 进行数据操作，你需要添加如下配置：
                //可选项，你不需要再次配置 x.UseSqlServer 了
                x.UseEntityFramework<AdncDbContext>(option =>
                {
                    option.TableNamePrefix = tableNamePrefix;
                });
                //CAP支持 RabbitMQ、Kafka、AzureServiceBus 等作为MQ，根据使用选择配置：
                x.UseRabbitMQ(option =>
                {
                    option.HostName = _rabbitMqConfig.HostName;
                    option.VirtualHost = _rabbitMqConfig.VirtualHost;
                    option.Port = _rabbitMqConfig.Port;
                    option.UserName = _rabbitMqConfig.UserName;
                    option.Password = _rabbitMqConfig.Password;
                });
                x.Version = _serviceInfo.Version;
                //默认值：cap.queue.{程序集名称},在 RabbitMQ 中映射到 Queue Names。
                x.DefaultGroup = groupName;
                //默认值：60 秒,重试 & 间隔
                //在默认情况下，重试将在发送和消费消息失败的 4分钟后 开始，这是为了避免设置消息状态延迟导致可能出现的问题。
                //发送和消费消息的过程中失败会立即重试 3 次，在 3 次以后将进入重试轮询，此时 FailedRetryInterval 配置才会生效。
                x.FailedRetryInterval = 60;
                //默认值：50,重试的最大次数。当达到此设置值时，将不会再继续重试，通过改变此参数来设置重试的最大次数。
                x.FailedRetryCount = 50;
                //默认值：NULL,重试阈值的失败回调。当重试达到 FailedRetryCount 设置的值的时候，将调用此 Action 回调
                //，你可以通过指定此回调来接收失败达到最大的通知，以做出人工介入。例如发送邮件或者短信。
                x.FailedThresholdCallback = (failed) =>
                {
                    //todo
                };
                //默认值：24*3600 秒（1天后),成功消息的过期时间（秒）。 
                //当消息发送或者消费成功时候，在时间达到 SucceedMessageExpiredAfter 秒时候将会从 Persistent 中删除，你可以通过指定此值来设置过期的时间。
                x.SucceedMessageExpiredAfter = 24 * 3600;
                //默认值：1,消费者线程并行处理消息的线程数，当这个值大于1时，将不能保证消息执行的顺序。
                x.ConsumerThreadCount = 1;
                x.UseDashboard(x=>
                {
                    x.PathMatch = $"/{_serviceInfo.ServiceName}/cap";
                    x.Authorization = new IDashboardAuthorizationFilter[] {
                        new LocalRequestsOnlyAuthorizationFilter()
                        ,
                        new CapDashboardAuthorizationFilter()
                    };
                });
                //必须是生产环境并且基于docker发布才注册cap服务到consul
                if ((_env.IsProduction() || _env.IsStaging())
                    && _consulConfig.IsDocker)
                {
                    x.UseDiscovery(x =>
                    {
                        var consulAdderss = new Uri(_consulConfig.ConsulUrl);
                        var listenHostAndPort = Environment.GetEnvironmentVariable("DOCKER_LISTEN_HOSTANDPORT");
                        var currenServerAddress = new Uri(listenHostAndPort);
                        x.DiscoveryServerHostName = consulAdderss.Host;
                        x.DiscoveryServerPort = consulAdderss.Port;
                        x.CurrentNodeHostName = currenServerAddress.Host;
                        x.CurrentNodePort = currenServerAddress.Port;
                        //x.NodeId = currenServerAddress.Host.Replace(".", string.Empty) + currenServerAddress.Port;
                        x.NodeId = "007";
                        x.NodeName = $"{_serviceInfo.ServiceFullName}-cap";
                        x.MatchPath = $"/{_serviceInfo.ServiceName}/cap";
                    });
                }
            });

```

**Comment by xiangxiren** [comment]
在我的测试环境中，并不能复现这个问题
![image](https://user-images.githubusercontent.com/12774053/97068677-637cd780-15fc-11eb-8c9a-8207bbd8d153.png)

**Comment by AlphaYu** [comment]
@xiangxiren 升级到3.11启动报错的原因我找到了。是mysqlconnector版本冲突的原因。
![image](https://user-images.githubusercontent.com/23010680/97085985-5c34e880-1653-11eb-8a89-7663472881f2.png)
![image](https://user-images.githubusercontent.com/23010680/97085999-67881400-1653-11eb-9402-5ac35f5ac384.png)
Pomelo.EntityFrameworkCore.MySql 最新版的mysqlconnector是>=0.69.9&&<1.0.0，cap最新版mysqlconnector是>=1.0.1，cap 3.0.4版是>0.60.3

谢谢你们热心回复。冲突的问题我自己解决吧。
