### ISSUE TITLE
Only MySqlParameter objects may be stored

### ISSUE THREAD

**Issue by AmayerGogh** [dotnetcore/CAP#735]
`    at MySql.Data.MySqlClient.MySqlParameterCollection.Add(Object value)
   at DotNetCore.CAP.MySql.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams) in E:\CodeCopy\CAP-master\src\DotNetCore.CAP.MySql\IDbConnection.Extensions.cs:line 25
   at DotNetCore.CAP.MySql.MySqlDataStorage.StoreMessage(String name, Message content, Object dbTransaction) in E:\CodeCopy\CAP-master\src\DotNetCore.CAP.MySql\IDataStorage.MySql.cs:line 90
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, IDictionary`2 headers) in E:\CodeCopy\CAP-master\src\DotNetCore.CAP\Internal\ICapPublisher.Default.cs:line 102
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, String callbackName) in E:\CodeCopy\CAP-master\src\DotNetCore.CAP\Internal\ICapPublisher.Default.cs:line 56
   at CCode.AdminBase.Controllers.PublishController.SendMessage(ICapPublisher capBus) in E:\Amayer\Cms\vnext\Services\CCode.AdminBase\Controllers\PublishController.cs:line 36
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()`

![image](https://user-images.githubusercontent.com/20901966/101299807-71b24a80-386e-11eb-9088-69e6645e79cb.png)

in DotNetCore.CAP.MySql.MySqlDataStorage   this function ### StoreMessage throw exception

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
