### ISSUE TITLE
Kafka subscribing

### ISSUE THREAD

**Issue by KovtunV** [dotnetcore/CAP#744]
Hi, when I use kafka can't subscribe a topic.

I have two webApi projects

1. webApi1: `ICapPublisher.Publish("testTopic", some object);`
2. webApi2: 
```csharp 
public class TestHandler : ICapSubscribe 
{
        [CapSubscribe("testTopic")]
        public Task<ResponseModel> HandleAsync(RequestModel model)
        {
            return Task.FromResult(new ResponseModel(model.Age * 100));
        }
} 
```

- If I start **webApi2** and then run **webApi1** with publishing **testTopic**, I won't get a message.
- If I start **webApi1** with publishing **testTopic** and then start **webApi2** , It will work fine.

Topic name should be unique, due to the fact that if I don't get a message in **webApi2** and then restart a project, it will work.
With RabbitMQ it works fine whatever I do.
Is it a bug or I use kafka incorrectly?

**Comment by yang-xiaodong** [comment]
Hello,  I can't reproduce your issue. Do you have this exception?

```
fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
      Broker: Unknown topic or partition
      Confluent.Kafka.ConsumeException: Broker: Unknown topic or partition
         at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
         at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
         at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
         at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_0.<Start>b__0()
```

**Comment by KovtunV** [comment]
Nope, but I have this:
``` csharp
DotNetCore.CAP.Internal.ConsumerRegister: Error: Broker: Unknown topic or partition

Confluent.Kafka.ConsumeException: Broker: Unknown topic or partition
   at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)
   at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)
   at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_0.<Start>b__0()
```

It happens for **new topic name** where I haven't sent message yet. Like I've written in first point: "If I start webApi2 and then run webApi1 with publishing testTopic, I won't get a message."

**Comment by yang-xiaodong** [comment]
This is a known issue, please refer to: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366
