### ISSUE TITLE
事务(进程 ID 234)与另一个进程被死锁在 锁 | 通信缓冲区 资源上，并且已被选作死锁牺牲品。请重新运行该事务。

### ISSUE THREAD

**Issue by kisshexuxia** [dotnetcore/CAP#821]
warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
      Processor 'DotNetCore.CAP.SqlServer.SqlServerCollectProcessor' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): 事务(进程 ID 234)与另一个进程被死锁在 锁 | 通信缓冲区 资源上，并且已被选作死锁牺牲品。请重新运行该事务。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at DotNetCore.CAP.SqlServer.SqlServerCollectProcessor.ProcessAsync(ProcessingContext context)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
ClientConnectionId:805ca984-793a-430b-ac32-0cb5a0c49563
Error Number:1205,State:52,Class:13

当数据大于3W条 Cap.Published和Cap.Received 有时候就出现这个问题了

**Comment by luox78** [comment]
我也碰到了这个问题，每天量20w左右，报错500左右，问题堆栈有两处
 at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery (Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQuery (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage+<DeleteExpiresAsync>d__12.MoveNext (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at DotNetCore.CAP.Processor.CollectorProcessor+<ProcessAsync>d__7.MoveNext (DotNetCore.CAP, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor+<ProcessAsync>d__3.MoveNext (DotNetCore.CAP, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)


 at Microsoft.Data.SqlClient.SqlDataReader.Read (Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage.<GetMessagesOfNeedRetryAsync>b__18_0 (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteReader (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage+<GetMessagesOfNeedRetryAsync>d__18.MoveNext (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at DotNetCore.CAP.SqlServer.SqlServerDataStorage+<GetPublishedMessagesOfNeedRetry>d__13.MoveNext (DotNetCore.CAP.SqlServer, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor+<GetSafelyAsync>d__9`1.MoveNext (DotNetCore.CAP, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null)

**Comment by yang-xiaodong** [comment]
Hello, please provide sample code so that we can reproduce this problem

**Comment by kisshexuxia** [comment]
这个数据一多（才4W多数据），做DELETE操作、那边还在UPDATE 就锁住了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 事务(进程 ID 234)与另一个进程被死锁在 锁 | 通信缓冲区 资源上，并且已被选作死锁牺牲品。请重新运行该事务。 (#821)





 
Hello, please provide sample code so that we can reproduce this problem

**Comment by yang-xiaodong** [comment]
DELETE 和 UPDATE 操作的又不是相同的数据，为什么会锁？

**Comment by kisshexuxia** [comment]
1.我这边sp_who显示很多BLK的数据，解锁解掉又出现新的锁，只能把表名改掉，在重新创建表才能解锁。
2.有5个微服务使用了CAP是不是，每个服务SucceedMessageExpiredAfter都是默认一天的，是不是同事在删除。
3.后来同事把SucceedMessageExpiredAfter调整为30天，然后写了个作业自己去删除delete&nbsp; from&nbsp; [Cap].[Published]&nbsp; where&nbsp; datediff(MINUTE,added,getdate())&gt;=30，但是还是会出现锁表这个作业失败
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 事务(进程 ID 234)与另一个进程被死锁在 锁 | 通信缓冲区 资源上，并且已被选作死锁牺牲品。请重新运行该事务。 (#821)





 
DELETE 和 UPDATE 操作的又不是相同的数据，为什么会锁？

**Comment by yang-xiaodong** [comment]
1、提供使用的CAP版本以及使用的数据库版本
2、提供异常详细描述，堆栈，报错信息
3、有无大量状态为失败的消息在表中？
4、最好提供可供复现的步骤，如果只是有时候，我也没办法

**Comment by luox78** [comment]
你好，我发现是表数据变多的时候，多台机器一起查询或者执行sql因为加锁的原因会很慢，为什么不考虑在初始化表的时候在某些字段上加索引呢

**Comment by kisshexuxia** [comment]
我现在只能写作业，2点，12点，18点删除下表数据

**Comment by kisshexuxia** [comment]
你手动加索引了吗？怎么加的，估计是传输的content字段内容过多查询慢了

**Comment by luox78** [comment]
你没必要手动写job删啊，你把两个表expireat都加上索引就能正常删了，截图了系统监控的效果
![image](https://user-images.githubusercontent.com/29404988/113860627-d22fa500-97d8-11eb-93ea-ac2c79f72860.png)

**Comment by yang-xiaodong** [comment]
请尝试在 `ExpiresAt` 添加非聚集索引，如果问题依旧，请重新打开此Issue，并提供必要信息。 现在我将此issue关闭。
