### ISSUE TITLE
InvalidCastException using unrelated components

### ISSUE THREAD

**Issue by flipdoubt** [dotnetcore/CAP#844]
I believe this is related to my other issue, but now I'm getting different `InvalidCastException` errors in other components that use `SqlConnection`. As the following stack trace shows, there is no application code involved, just CAP and Hangfire:
```
TYPE: System.InvalidCastException
MSG: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.

Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.
   at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\Diagnostics\DiagnosticObserver.cs:line 41
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteTransactionCommitAfter(DiagnosticListener this, Guid operationId, IsolationLevel isolationLevel, SqlConnection connection, String operation)
   at System.Data.SqlClient.SqlTransaction.Commit()
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass35_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass14_0.<Create>b__3(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<RetryOnException>b__0(Int32 attempt)
   at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)
```

**Comment by flipdoubt** [comment]
When I remove the project that calls `AddCap`, the error does not occur.

**Comment by yang-xiaodong** [comment]
Duplicate of #739

**Comment by flipdoubt** [comment]
Hi, @yang-xiaodong. I see someone reported issues integrating with Hangfire, but the fact remains the DiagnosticObserver does a hard cast that fails when the connection from non-CAP code uses a different kind of connection. I fixed this in PR #845. Could you review and consider accepting this? Thanks.

**Comment by yang-xiaodong** [comment]
Hi David, 
Thanks for you PR!  Do you need us to release a new preview version for testing?

**Comment by flipdoubt** [comment]
Yes, please. That would be great.

**Comment by yang-xiaodong** [comment]
Version  `5.0.2-preview-136262472` is released to nuget in a few minutes ago, thanks

**Comment by flipdoubt** [comment]
Thanks! Got it and verified this fixes my issue with Hangfire.
