### ISSUE TITLE
relation "cap.published" does not exist

### ISSUE THREAD

**Issue by blenddata** [dotnetcore/CAP#854]
Hi,
Scheme does not appear to be properly initiated, it can't find the published table.
I checked the connections (PostgreSQL and RabbitMQ) both are fine.

![image](https://user-images.githubusercontent.com/50766350/117143279-e78ef380-adc5-11eb-8d6b-89bfd63eaa0b.png)

`INSERT INTO "cap"."published" ("Id","Version","Name","Content","Retries","Added","ExpiresAt","StatusName")VALUES($1,'v1',$2,$3,$4,$5,$6,$7)`

>    at Npgsql.NpgsqlConnector.<<ReadMessage>g__ReadMessageLong|194_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Npgsql.NpgsqlDataReader.<NextResult>d__44.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__105.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__105.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__93.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at DotNetCore.CAP.PostgreSql.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.PostgreSql.PostgreSqlDataStorage.StoreMessage(String name, Message content, Object dbTransaction)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, IDictionary`2 headers)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, String callbackName)
   at DotNetCore.CAP.Internal.CapPublisher.<>c__DisplayClass12_0`1.<PublishAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by blenddata** [comment]
I initiated it manually and it's working now

```
 public CapPipeline(ICapPublisher capPublisher,ILogger<PostgreSqlStorageInitializer> logger,
        IOptions<PostgreSqlOptions> options)
        {
            var init = new PostgreSqlStorageInitializer(logger, options);
            init.InitializeAsync(default);

            _capPublisher = capPublisher;
        }
```
I'm adding Cap services from unit test project, idk maybe it can be the cause.

**Comment by xiangxiren** [comment]
The database initialization operation will be performed when the program is started. You should check the log to see if there is any initialization failure information.

**Comment by xiangxiren** [comment]
No response,Close

**Comment by xiangxiren** [comment]
No response, Close.

**Comment by blenddata** [comment]
Actually it was because of `Bootstrap` 
in the unit test you have to Bootstrap it manually.
https://github.com/dotnetcore/CAP/issues/860#issuecomment-838020712
