### ISSUE TITLE
RabbitMQ Connection close forced

### ISSUE THREAD

**Issue by hetaoos** [dotnetcore/CAP#861]
Hi, After upgrading from 5.0.0 to 5.0.1 or 5.0.2, cap cannot connect to the RabbitMQ server and reports "Connection close forced" exception. 

When downgrade to 5.0.0, the exception does not occur. 

RabbitMQ 3.8.14 Erlang 23.3.1

log:
```
2021-05-09T02:56:33.151799434Z fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
2021-05-09T02:56:33.151825096Z       The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0
2021-05-09T02:56:33.151833874Z       RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0
2021-05-09T02:56:33.151843336Z          at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
2021-05-09T02:56:33.151850829Z          at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
2021-05-09T02:56:33.151858402Z          at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
2021-05-09T02:56:33.151866082Z          at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Subscribe(IEnumerable`1 topics)
2021-05-09T02:56:33.151873324Z          at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_1.<Start>b__2()
2021-05-09T02:56:33.158342427Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.158368148Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.164347969Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.164397986Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.170505352Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.170526837Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.173584918Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.173598361Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.173611282Z warn: DotNetCore.CAP.Internal.ConsumerRegister[0]
2021-05-09T02:56:33.173616072Z       RabbitMQ consumer cancelled. --> amq.ctag-LHdQUCASJam_u8IiBY2T5w
2021-05-09T02:56:33.173620416Z warn: DotNetCore.CAP.Internal.ConsumerRegister[0]
2021-05-09T02:56:33.173624933Z       RabbitMQ consumer shutdown. --> Connection close forced
2021-05-09T02:56:33.173927533Z fail: DotNetCore.CAP.Internal.ConsumerRegister[0]
2021-05-09T02:56:33.173950761Z       The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0
2021-05-09T02:56:33.173957839Z       RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0
2021-05-09T02:56:33.173964031Z          at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
2021-05-09T02:56:33.173970886Z          at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
2021-05-09T02:56:33.173976659Z          at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
2021-05-09T02:56:33.173982449Z          at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Subscribe(IEnumerable`1 topics)
2021-05-09T02:56:33.173987975Z          at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_1.<Start>b__2()
2021-05-09T02:56:33.179440061Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.179467580Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.185306684Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.185332453Z       RabbitMQ client connection closed! --> Connection close forced
2021-05-09T02:56:33.191531529Z warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
2021-05-09T02:56:33.191562287Z       RabbitMQ client connection closed! --> Connection close forced
```

**Comment by rsh924** [comment]
same problem
Unhandled exception. RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0

at RabbitMQ.Client.Impl.SessionBase.Transmit(OutgoingCommand& cmd)

at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, ReadOnlyMemory`1 body)

at RabbitMQ.Client.Framing.Impl.Model.BasicReject(UInt64 deliveryTag, Boolean requeue)

at RabbitMQ.Client.Impl.RecoveryAwareModel.BasicReject(UInt64 deliveryTag, Boolean requeue)

at RabbitMQ.Client.Impl.AutorecoveringModel.BasicReject(UInt64 deliveryTag, Boolean requeue)

at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Reject(Object sender)

at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_0.<<RegisterMessageProcessor>b__0>d.MoveNext()

--- End of stack trace from previous location ---

at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)

at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)

at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)

at System.Threading.QueueUserWorkItemCallback.Execute()

at System.Threading.ThreadPoolWorkQueue.Dispatch()

at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by hetaoos** [comment]
I think I found the reason, it may be that the queue name contains `-` char.

**Comment by hetaoos** [comment]
Use the following code to reproduce this problem:
```cs
[NonAction]
[CapSubscribe("sample.rabbitmq.mongodb")]
[CapSubscribe("n10", Group = "g10")]
[CapSubscribe("n11", Group = "g11")]
[CapSubscribe("n12", Group = "g12")]
[CapSubscribe("n13", Group = "g13")]
[CapSubscribe("n14", Group = "g14")]
[CapSubscribe("n15", Group = "g15")]
[CapSubscribe("n16", Group = "g16")]
[CapSubscribe("n17", Group = "g17")]
[CapSubscribe("n18", Group = "g18")]
[CapSubscribe("n19", Group = "g19")]
[CapSubscribe("n20", Group = "g20")]
[CapSubscribe("n21", Group = "g21")]
[CapSubscribe("n22", Group = "g22")]
[CapSubscribe("n23", Group = "g23")]
[CapSubscribe("n24", Group = "g24")]
[CapSubscribe("n25", Group = "g25")]
public void ReceiveMessage(dynamic a)
{
    Console.WriteLine($@"{DateTime.Now}, Subscriber invoked, Sent time:{a}");
}
```

![image](https://user-images.githubusercontent.com/1094462/117661755-5a86d880-b1d1-11eb-9b65-0208d68f721a.png)

**Comment by hetaoos** [comment]
@yang-xiaodong 我看了下源码，发现 `ConnectionChannelPool.GetConnection()` 有点问题。
在并发执行时，由于没有对该方法进行锁定，每次请求返回的连接可能是不同的。而 `_connection` 变量只能保存最后一次请求的连接。
在顺序执行时，则会返回相同的连接。

如果整个系统完全复用一个连接，需要将`ConnectionChannelPool`中的代码改成这样：
```cs
public IConnection GetConnection()
{
    lock (SLock)
    {
        if (_connection != null && _connection.IsOpen)
        {
            return _connection;
        }
        _connection?.Dispose();

        _connection = _connectionActivator();
        return _connection;
    }
}

public void Dispose()
{
    _maxSize = 0;

    while (_pool.TryDequeue(out var context))
    {
        context.Dispose();
    }
    _connection?.Dispose();
}
```
