### ISSUE TITLE
not automatically receive

### ISSUE THREAD

**Issue by penjay** [dotnetcore/CAP#866]
Send success, but accumulated in "issued", not automatically receiving (consumption), need to restart the host program to trigger consumption, why?

**Comment by penjay** [comment]
Error logs:

2021-05-11 22:57:25.7895|0|ERROR|DotNetCore.CAP.Internal.ConsumerRegister|Already closed: The AMQP operation was interrupted: AMQP close-reason,
 initiated by Application, code=200, text='Connection close forced', classId=0, methodId=0 RabbitMQ.Client.Exceptions.AlreadyClosedException:
  Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text='Connection close forced', 
  classId=0, methodId=0
   at RabbitMQ.Client.Impl.SessionBase.Transmit(OutgoingCommand& cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Subscribe(IEnumerable`1 topics)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_1.<Start>b__2()|url: |action: |DotNetCore.CAP.Internal.ConsumerRegister+<>c__DisplayClass17_1.<Start>b__2| body:

**Comment by xiangxiren** [comment]
#861

**Comment by penjay** [comment]
> #861

Thank you! I downgraded to 5.0.0 ,^_^

**Comment by yang-xiaodong** [comment]
Good!  Now I close the replica, let's discuss it in the main thread
