### ISSUE TITLE
在 READ COMMITTED 或 REPEATABLE READ 隔离级别上只能指定 READPAST 锁

### ISSUE THREAD

**Issue by chaiziqi** [dotnetcore/CAP#92]
使用SqlServer2012数据库，log出现如下异常信息：
warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
      Processor 'DotNetCore.CAP.Processor.PublishQueuer' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): 在 READ COMMITTED 或 REPEATABLE READ 隔离级别上只能指定 READPAST 锁。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass186_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryRowAsync>d__32`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 456
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.<GetNextPublishedMessageToBeEnqueuedAsync>d__8.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP.SqlServer\SqlServerStorageConnection.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.Processor.PublishQueuer.<ProcessAsync>d__6.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.PublishQueuer.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.<ProcessAsync>d__3.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.InfiniteRetry.cs:line 25
ClientConnectionId:e95340c7-3036-4af8-b037-9026c0b6f245
Error Number:650,State:1,Class:16
warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
      Processor 'DotNetCore.CAP.Processor.SubscribeQueuer' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): 在 READ COMMITTED 或 REPEATABLE READ 隔离级别上只能指定 READPAST 锁。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass186_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryRowAsync>d__32`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 456
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.<GetNextReceivedMessageToBeEnqueuedAsync>d__12.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP.SqlServer\SqlServerStorageConnection.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.Processor.SubscribeQueuer.<ProcessAsync>d__6.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.SubscribeQueuer.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.<ProcessAsync>d__3.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.InfiniteRetry.cs:line 25
ClientConnectionId:e95340c7-3036-4af8-b037-9026c0b6f245
Error Number:650,State:1,Class:16
warn: DotNetCore.CAP.Processor.InfiniteRetryProcessor[1]
      Processor 'DotNetCore.CAP.Processor.FailedProcessor' failed. Retrying...
System.Data.SqlClient.SqlException (0x80131904): 在 READ COMMITTED 或 REPEATABLE READ 隔离级别上只能指定 READPAST 锁。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass186_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__31`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.SqlServer.SqlServerStorageConnection.<GetFailedReceivedMessages>d__13.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP.SqlServer\SqlServerStorageConnection.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DotNetCore.CAP.Processor.FailedProcessor.<ProcessReceivedAsync>d__11.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.Failed.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Processor.FailedProcessor.<ProcessAsync>d__9.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.Failed.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.<ProcessAsync>d__3.MoveNext() in E:\软件项目\框架学习\Identity Server\aspnet-core\src\CAP\src\DotNetCore.CAP\Processor\IProcessor.InfiniteRetry.cs:line 25
ClientConnectionId:90f742d9-7350-4aa5-97f3-f02155d80ad5
Error Number:650,State:1,Class:16

**Comment by doufeng007** [comment]
@chaiziqi    你成功了嘛？  在abp上用CAP？  我现在也在搞这个 但是始终拿不到ef 的 datacontext。
