### ISSUE TITLE
Unable to start CAP with Azure ServiceBus because subscription name character limit is exceeded

### ISSUE THREAD

**Issue by kaposhkin** [dotnetcore/CAP#933]
I guess CAP generates a subscription name based on assembly name. We follow company naming standard and in our case the name is pretty long (ns.xcompany.webapp.storagemanagement.api).
Would be good to have some smart logic to truncate a subscription name or to allow a user to configure it.

Stack Trace:

`DotNetCore.CAP.Internal.Bootstrapper[0]
      Starting the processors throw an exception.
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> System.ArgumentOutOfRangeException: Entity path 'cap.queue.ns.xcompany.webapp.storagemanagement.api.v1' exceeds the '50' character limit. (Parameter 'subscriptionName')
   at Microsoft.Azure.ServiceBus.EntityNameHelper.CheckValidEntityName(String entityName, Int32 maxEntityNameLength, Boolean allowSeparator, String paramName)
   at Microsoft.Azure.ServiceBus.EntityNameHelper.CheckValidSubscriptionName(String subscriptionName, String paramName)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.SubscriptionExistsAsync(String topicPath, String subscriptionName, CancellationToken cancellationToken)
   at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClient.ConnectAsync()
   at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClientFactory.Create(String groupId)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClientFactory.Create(String groupId)
   at DotNetCore.CAP.Internal.ConsumerRegister.Start()
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapCoreAsync()`

**Comment by yang-xiaodong** [comment]
You can set `DefaultGroupName` option to use short names

https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#defaultgroupname

**Comment by kaposhkin** [comment]
Closing it? But it's just workaround above that doesn't solve the problem if an assembly name is longer than 50 characters.
I reckon that at least truncating a subscription name would be a better option than doing nothing.
