### ISSUE TITLE
CAP startup exception if there are some failed message in the database.

### ISSUE THREAD

**Issue by 54czp** [dotnetcore/CAP#939]
BUG description(问题描述)
1.CAP startup in ConfigureServices(), then CAP begin consume message if there are some failed message in the database.
2.But the application has not been initialized at this time, the construction method in consumer class will throw a NullReferenceException when CAP call CapSubscribe methord.

Reproducible Steps(复现步骤)
1.There is one producer (p1) and one consumer (c1) in the message queue(mq).
2.p1 send a message to c1, then stop the program before c1 consume the message. 
3.restart the program,the construction method in consumer class will throw a NullReferenceException

Configuration(配置)
private void ConfigureCAP(ServiceConfigurationContext context, IConfiguration configuration)
        {
            context.Services.AddCap(x =>
            {
                x.UseMySql(configuration["Cap:ConnectionStrings"]);

                x.UseRabbitMQ(cfg =>
                {
                    cfg.HostName = configuration["Cap:RabbitMQ:Host"];
                    cfg.Port = int.Parse(configuration["Cap:RabbitMQ:Port"]);
                    cfg.UserName = configuration["Cap:RabbitMQ:UserName"];
                    cfg.Password = configuration["Cap:RabbitMQ:Password"];
                    cfg.VirtualHost = configuration["Cap:RabbitMQ:VirtualHost"];
                    cfg.QueueArguments.MessageTTL = int.Parse(configuration["Cap:RabbitMQ:QueueArguments.MessageTTL"]);
                    cfg.QueueArguments.QueueMode = configuration["Cap: RabbitMQ: QueueArguments.QueueMode"];
                });
                x.UseDashboard();
                x.ConsumerThreadCount = int.Parse(configuration["Cap:ConsumerThreadCount"]);
                x.FailedRetryCount = int.Parse(configuration["Cap:FailedRetryCount"]);
                x.FailedRetryInterval = int.Parse(configuration["Cap:FailedRetryInterval"]);
                x.SucceedMessageExpiredAfter = int.Parse(configuration["Cap:SucceedMessageExpiredAfter"]);
            });
        }

  "Cap": {
    "ConnectionStrings": "Server=xxxxxxxxx",
    "RabbitMQ:Host": "xxxxxxxxxxxx",
    "RabbitMQ:Port": "xxxx",
    "RabbitMQ:UserName": "xxxxxxxx",
    "RabbitMQ:Password": "xxxxxxxx",
    "RabbitMQ:VirtualHost": "my_vhost",
    "RabbitMQ:QueueArguments.MessageTTL": 864000000, //Default 864000000 ms (消息保存十天).
    "RabbitMQ:QueueArguments.QueueMode": "default", //"default"/"lazy"延迟队列尝试尽可能早地将消息移动到磁盘。这意味着在正常操作的大多数情况下，RAM 中保留的消息要少得多。这是以增加磁盘 I/O 为代价的。
    "ConsumerThreadCount": 1, //默认值：1。消费者线程并行处理消息的线程数，当这个值大于1时，将不能保证消息执行的顺序。
    "FailedRetryCount": 8, //默认值：50。重试的最大次数。当达到此设置值时，将不会再继续重试，通过改变此参数来设置重试的最大次数。
    "FailedRetryInterval": 1, //默认值：60秒。重试的时间间隔
    "SucceedMessageExpiredAfter": 86400 //数据库保存消息时间。默认值：24*3600秒(一天后) 成功消息的过期时间（秒）。 当消息发送或者消费成功时候，在时间达到 SucceedMessageExpiredAfter 秒时候将会从 Persistent 中删除.
  }

Error Log(错误日志):
2021-07-12 18:36:23.440 +08:00 [INF] Starting Message.Host
2021-07-12 18:36:27.415 +08:00 [INF] User profile is available. Using 'xxxxxxxxxxxxxxxxxxxxxx/DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2021-07-12 18:36:27.450 +08:00 [DBG] RabbitMQ configuration:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2021-07-12 18:36:27.622 +08:00 [DBG] ### CAP background task is starting.
2021-07-12 18:36:28.068 +08:00 [DBG] Ensuring all create database tables script are applied.
2021-07-12 18:36:28.549 +08:00 [INF] Starting the processing server.
2021-07-12 18:36:28.561 +08:00 [DBG] Transport connection checking...
2021-07-12 18:36:28.563 +08:00 [DBG] Transport connection healthy!
2021-07-12 18:36:28.859 +08:00 [INF] RabbitMQ consumer registered. --> amq.ctag-9hhQOtR1P3-gohSYiUtgQg
2021-07-12 18:36:28.990 +08:00 [DBG] Executing subscriber method : AliyunSendSms
2021-07-12 18:36:33.215 +08:00 [ERR] An exception occurred while executing the subscription method. Topic:Message.Send.SMS, Id:1412980035625725952
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: An exception was thrown while activating λ:Message.MqManagement.IConsumer[] -> Message.MqManagement.Consumer -> Castle.Proxies.SmsRecordAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Message.MqManagement.IConsumer[] -> Message.MqManagement.Consumer -> Castle.Proxies.SmsRecordAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Message.DDD.SmsRecordManagement.SmsRecordManager)' on type 'SmsRecordAppServiceProxy'.
 ---> System.Exception: 系统未初始化
   at Message.MessageAppService..ctor() in E:\abp\Debug\MicroServices\Message\Message.Application\MessageAppService.cs:line 24
   at Message.SmsRecordManagement.SmsRecordAppService..ctor(SmsRecordManager smsRecordManager) in E:\abp\Debug\MicroServices\Message\Message.Application\SmsRecordManagement\SmsRecordAppService.cs:line 35
   at lambda_method223(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at DotNetCore.CAP.Internal.SubscribeInvoker.GetInstance(IServiceProvider provider, ConsumerContext context)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at DotNetCore.CAP.Internal.SubscribeInvoker.GetInstance(IServiceProvider provider, ConsumerContext context)
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
2021-07-12 18:36:33.508 +08:00 [DBG] Collecting expired data from table: cap.published
2021-07-12 18:36:33.600 +08:00 [DBG] Collecting expired data from table: cap.received
2021-07-12 18:36:33.834 +08:00 [INF] ### CAP started!
2021-07-12 18:36:33.847 +08:00 [INF] Loaded ABP modules:
2021-07-12 18:36:33.850 +08:00 [INF] - Volo.Abp.Castle.AbpCastleCoreModule
2021-07-12 18:36:33.851 +08:00 [INF] - Volo.Abp.Autofac.AbpAutofacModule
2021-07-12 18:36:33.853 +08:00 [INF] - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
2021-07-12 18:36:33.854 +08:00 [INF] - Volo.Abp.Validation.AbpValidationAbstractionsModule
2021-07-12 18:36:33.855 +08:00 [INF] - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
2021-07-12 18:36:33.857 +08:00 [INF] - Volo.Abp.Uow.AbpUnitOfWorkModule
2021-07-12 18:36:33.858 +08:00 [INF] - Volo.Abp.Data.AbpDataModule
2021-07-12 18:36:33.859 +08:00 [INF] - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
2021-07-12 18:36:33.860 +08:00 [INF] - Volo.Abp.Security.AbpSecurityModule
2021-07-12 18:36:33.861 +08:00 [INF] - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
2021-07-12 18:36:33.862 +08:00 [INF] - Volo.Abp.Settings.AbpSettingsModule
2021-07-12 18:36:33.863 +08:00 [INF] - Volo.Abp.Timing.AbpTimingModule
2021-07-12 18:36:33.864 +08:00 [INF] - Volo.Abp.Json.AbpJsonModule
2021-07-12 18:36:33.865 +08:00 [INF] - Volo.Abp.Threading.AbpThreadingModule
2021-07-12 18:36:33.866 +08:00 [INF] - Volo.Abp.Auditing.AbpAuditingModule
2021-07-12 18:36:33.867 +08:00 [INF] - Volo.Abp.EventBus.AbpEventBusModule
2021-07-12 18:36:33.868 +08:00 [INF] - Volo.Abp.Guids.AbpGuidsModule
2021-07-12 18:36:33.870 +08:00 [INF] - Volo.Abp.ObjectMapping.AbpObjectMappingModule
2021-07-12 18:36:33.871 +08:00 [INF] - Volo.Abp.Localization.AbpLocalizationModule
2021-07-12 18:36:33.872 +08:00 [INF] - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
2021-07-12 18:36:33.874 +08:00 [INF] - Volo.Abp.Specifications.AbpSpecificationsModule
2021-07-12 18:36:33.875 +08:00 [INF] - Volo.Abp.Domain.AbpDddDomainModule
2021-07-12 18:36:33.876 +08:00 [INF] - Volo.Abp.EntityFrameworkCore.AbpEntityFrameworkCoreModule
2021-07-12 18:36:33.877 +08:00 [INF] - Volo.Abp.EntityFrameworkCore.MySQL.AbpEntityFrameworkCoreMySQLModule
2021-07-12 18:36:33.878 +08:00 [INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
2021-07-12 18:36:33.879 +08:00 [INF] - Volo.Abp.AuditLogging.AbpAuditLoggingDomainModule
2021-07-12 18:36:33.880 +08:00 [INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
2021-07-12 18:36:33.882 +08:00 [INF] - Volo.Abp.Serialization.AbpSerializationModule
2021-07-12 18:36:33.883 +08:00 [INF] - Volo.Abp.Caching.AbpCachingModule
2021-07-12 18:36:33.886 +08:00 [INF] - Volo.Abp.SettingManagement.AbpSettingManagementDomainModule
2021-07-12 18:36:33.887 +08:00 [INF] - EasyAbp.Abp.WeChat.Common.AbpWeChatCommonModule
2021-07-12 18:36:33.888 +08:00 [INF] - EasyAbp.Abp.WeChat.Official.AbpWeChatOfficialModule
2021-07-12 18:36:33.889 +08:00 [INF] - Message.MessageDomainModule
2021-07-12 18:36:33.890 +08:00 [INF] - Volo.Abp.Application.AbpDddApplicationContractsModule
2021-07-12 18:36:33.891 +08:00 [INF] - Volo.Abp.Validation.AbpValidationModule
2021-07-12 18:36:33.892 +08:00 [INF] - Volo.Abp.Authorization.AbpAuthorizationModule
2021-07-12 18:36:33.894 +08:00 [INF] - Volo.Abp.Http.AbpHttpAbstractionsModule
2021-07-12 18:36:33.895 +08:00 [INF] - Volo.Abp.Features.AbpFeaturesModule
2021-07-12 18:36:33.896 +08:00 [INF] - Volo.Abp.Application.AbpDddApplicationModule
2021-07-12 18:36:33.897 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
2021-07-12 18:36:33.898 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
2021-07-12 18:36:33.902 +08:00 [INF] - Message.MessageApplicationContractsModule
2021-07-12 18:36:33.903 +08:00 [INF] - Volo.Abp.Minify.AbpMinifyModule
2021-07-12 18:36:33.904 +08:00 [INF] - Volo.Abp.Http.AbpHttpModule
2021-07-12 18:36:33.905 +08:00 [INF] - Volo.Abp.AspNetCore.AbpAspNetCoreModule
2021-07-12 18:36:33.907 +08:00 [INF] - Volo.Abp.ApiVersioning.AbpApiVersioningAbstractionsModule
2021-07-12 18:36:33.908 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
2021-07-12 18:36:33.909 +08:00 [INF] - Volo.Abp.UI.AbpUiModule
2021-07-12 18:36:33.910 +08:00 [INF] - Volo.Abp.GlobalFeatures.AbpGlobalFeaturesModule
2021-07-12 18:36:33.911 +08:00 [INF] - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcModule
2021-07-12 18:36:33.912 +08:00 [INF] - EasyAbp.Abp.WeChat.Official.HttpApi.AbpWeChatOfficialHttpApiModule
2021-07-12 18:36:33.913 +08:00 [INF] - Message.MessageHttpApiModule
2021-07-12 18:36:33.914 +08:00 [INF] - Volo.Abp.Http.Client.AbpHttpClientModule
2021-07-12 18:36:33.916 +08:00 [INF] - Volo.Abp.IdentityModel.AbpIdentityModelModule
2021-07-12 18:36:33.917 +08:00 [INF] - Volo.Abp.Http.Client.IdentityModel.AbpHttpClientIdentityModelModule
2021-07-12 18:36:33.919 +08:00 [INF] - Volo.Abp.AutoMapper.AbpAutoMapperModule
2021-07-12 18:36:33.920 +08:00 [INF] - Message.MessageApplicationModule
2021-07-12 18:36:33.921 +08:00 [INF] - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainModule
2021-07-12 18:36:33.923 +08:00 [INF] - Volo.Abp.PermissionManagement.EntityFrameworkCore.AbpPermissionManagementEntityFrameworkCoreModule
2021-07-12 18:36:33.924 +08:00 [INF] - Volo.Abp.SettingManagement.EntityFrameworkCore.AbpSettingManagementEntityFrameworkCoreModule
2021-07-12 18:36:33.926 +08:00 [INF] - Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingEntityFrameworkCoreModule
2021-07-12 18:36:33.927 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
2021-07-12 18:36:33.929 +08:00 [INF] - Volo.Abp.TenantManagement.AbpTenantManagementDomainModule
2021-07-12 18:36:33.930 +08:00 [INF] - Volo.Abp.TenantManagement.EntityFrameworkCore.AbpTenantManagementEntityFrameworkCoreModule
2021-07-12 18:36:33.932 +08:00 [INF] - Message.EntityFrameworkCore.MessageEntityFrameworkCoreModule
2021-07-12 18:36:33.933 +08:00 [INF] - Volo.Abp.AspNetCore.MultiTenancy.AbpAspNetCoreMultiTenancyModule
2021-07-12 18:36:33.934 +08:00 [INF] - Volo.Abp.AspNetCore.Serilog.AbpAspNetCoreSerilogModule
2021-07-12 18:36:33.936 +08:00 [INF] - Message.MessageHostModule
2021-07-12 18:36:34.968 +08:00 [INF] Initialized all ABP modules.
2021-07-12 18:36:35.021 +08:00 [INF] Now listening on: http://[::]:52041
2021-07-12 18:36:35.024 +08:00 [INF] Application started. Press Ctrl+C to shut down.
2021-07-12 18:36:35.025 +08:00 [INF] Hosting environment: Development

**Comment by yang-xiaodong** [comment]
Hello, What's your CAP version?

**Comment by yang-xiaodong** [comment]
No response, closed
