### ISSUE TITLE
use dashboard,problems caused by different versions

### ISSUE THREAD

**Issue by cdefg198** [dotnetcore/CAP#947]
DotNetCore.CAP:v5.1.1
DotNetCore.CAP.Dashboard:v3.1.2
Because my project is netcoreapp3.1,so can't use Dashboard v5.1.1.
exception:
`Category: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer
EventId: 2
RequestId: 80000083-0002-f700-b63f-84710c7967bb
RequestPath: /cap/received/succeeded
SpanId: |89d95084-4e31fbaed730fa4e.
TraceId: 89d95084-4e31fbaed730fa4e
ParentId: 

Connection ID "17798225737568747650", Request ID "80000083-0002-f700-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<DotNetCore.CAP.Monitoring.MessageDto> DotNetCore.CAP.Monitoring.IMonitoringApi.Messages(DotNetCore.CAP.Monitoring.MessageQueryDto)'.
   at DotNetCore.CAP.Dashboard.Pages.ReceivedPage.Execute()
   at DotNetCore.CAP.Dashboard.RazorPage.TransformText(String body)
   at DotNetCore.CAP.Dashboard.RazorPage.ToString()
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()`

so can we only use DotNetCore.CAP:v3.1.2?

**Comment by yang-xiaodong** [comment]
Yes, 5.x and 3.x are major version upgrades
